<script setup>
import { Trophy, Palette, Users, Sparkles, Heart, Lightbulb } from 'lucide-vue-next'
import sports from '../assets/images/beyond-class.jpg'
import creative from '../assets/images/creative-2.jpg'
import group from '../assets/images/group-work.jpg'
import fun from '../assets/images/funtime.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const text = pair => pair[language.value === 'bn' ? 1 : 0]
const activities = [
 {image:sports,icon:Trophy,title:['Sports & Active Play','খেলাধুলা'],body:['Movement and shared games encourage coordination, perseverance, and respect for others.','খেলাধুলা সমন্বয়, অধ্যবসায় ও অন্যের প্রতি শ্রদ্ধা গড়ে তোলে।']},
 {image:creative,icon:Palette,title:['Art & Creative Exploration','শিল্প ও সৃজনশীলতা'],body:['Making, drawing, and classroom projects give students opportunities to express ideas and explore their imagination.','আঁকা, তৈরি করা ও শ্রেণিকক্ষের প্রকল্প শিক্ষার্থীদের ভাব প্রকাশ ও কল্পনাশক্তি বিকাশের সুযোগ দেয়।']},
 {image:group,icon:Users,title:['Teamwork & Shared Learning','দলগত কাজ ও শিক্ষা'],body:['Working together helps learners listen, contribute, and take responsibility for a shared goal.','একসঙ্গে কাজ শিক্ষার্থীদের শুনতে, অংশ নিতে ও যৌথ লক্ষ্যের দায়িত্ব নিতে সাহায্য করে।']},
]
const benefits = [
 {icon:Sparkles,title:['Confidence','আত্মবিশ্বাস'],body:['Trying new experiences helps students recognise their strengths.','নতুন অভিজ্ঞতা শিক্ষার্থীদের নিজের সামর্থ্য চিনতে সাহায্য করে।']},
 {icon:Lightbulb,title:['Creativity','সৃজনশীলতা'],body:['Exploration creates space for original ideas and self-expression.','অন্বেষণ নতুন ধারণা ও আত্মপ্রকাশের সুযোগ তৈরি করে।']},
 {icon:Heart,title:['Wellbeing','সুস্থতা'],body:['Active participation supports movement, enjoyment, and connection.','সক্রিয় অংশগ্রহণ শরীরচর্চা, আনন্দ ও পারস্পরিক সম্পর্ক গড়ে তোলে।']},
 {icon:Users,title:['Responsibility & Teamwork','দায়িত্ববোধ ও দলগত দক্ষতা'],body:['Shared tasks build cooperation, patience, and practical life skills.','যৌথ কাজ সহযোগিতা, ধৈর্য ও জীবনদক্ষতা বাড়ায়।']},
]
</script>
<template>
 <div class="activities-page">
  <section class="activities-hero"><img :src="fun" :alt="text(['Students enjoying an activity at PIISC','পিআইআইএসসির শিক্ষার্থীদের আনন্দময় কার্যক্রম'])" fetchpriority="high"/><div class="activities-width hero-copy"><p class="activities-eyebrow">{{ text(['CO-CURRICULAR ACTIVITIES','সহশিক্ষা কার্যক্রম']) }}</p><h1>{{ text(['Learning beyond the classroom','শ্রেণিকক্ষের বাইরেও শিক্ষা']) }}</h1><p>{{ text(['At PIISC, creativity, play, and learning together complement academic life. We encourage students across the school and college to discover their strengths, care for others, and grow in confidence.','পিআইআইএসসিতে সৃজনশীলতা, খেলাধুলা ও একসঙ্গে শেখা প্রাতিষ্ঠানিক শিক্ষাকে সমৃদ্ধ করে। স্কুল ও কলেজের শিক্ষার্থীদের নিজের সামর্থ্য আবিষ্কার, অন্যের যত্ন ও আত্মবিশ্বাসের সঙ্গে বেড়ে উঠতে উৎসাহিত করি।']) }}</p></div></section>
  <section class="activities-width activities-section"><p class="activities-eyebrow">{{ text(['OUR ACTIVITIES','আমাদের কার্যক্রম']) }}</p><h2>{{ text(['Discover, participate, and grow.','আবিষ্কার, অংশগ্রহণ ও বিকাশ।']) }}</h2><p class="section-lead">{{ text(['Explore moments from PIISC school life. Ask the school about current activities and opportunities for your child’s grade.','পিআইআইএসসির স্কুলজীবনের কিছু মুহূর্ত দেখুন। আপনার সন্তানের শ্রেণির বর্তমান কার্যক্রম ও সুযোগ সম্পর্কে স্কুলের সঙ্গে কথা বলুন।']) }}</p><div class="activity-grid"><article v-for="activity in activities" :key="activity.title[0]"><img :src="activity.image" :alt="text(activity.title)" loading="lazy"/><div class="activity-copy"><span class="activity-icon"><component :is="activity.icon" :size="24" aria-hidden="true"/></span><h3>{{ text(activity.title) }}</h3><p>{{ text(activity.body) }}</p></div></article></div></section>
  <section class="benefits-section"><div class="activities-width"><p class="activities-eyebrow">{{ text(['WHY PARTICIPATION MATTERS','অংশগ্রহণের গুরুত্ব']) }}</p><h2>{{ text(['Skills that grow with your child','শিশুর সঙ্গে বেড়ে ওঠা দক্ষতা']) }}</h2><div class="benefit-grid"><article v-for="benefit in benefits" :key="benefit.title[0]"><span class="activity-icon"><component :is="benefit.icon" :size="23" aria-hidden="true"/></span><h3>{{ text(benefit.title) }}</h3><p>{{ text(benefit.body) }}</p></article></div></div></section>
  <section class="activities-width activities-section"><p class="activities-eyebrow">{{ text(['ACTIVITIES IN ACTION','কার্যক্রমের মুহূর্ত']) }}</p><h2>{{ text(['A glimpse of life at PIISC','পিআইআইএসসির জীবনের এক ঝলক']) }}</h2><div class="activity-gallery"><img v-for="item in activities" :key="item.image" :src="item.image" :alt="text(item.title)" loading="lazy"/><img :src="fun" :alt="text(['Fun time at PIISC','পিআইআইএসসিতে আনন্দের সময়'])" loading="lazy"/></div></section>
 </div>
</template>
<style scoped>
.activities-page{background:#fff}.activities-width{width:calc(100% - clamp(32px,6.5vw,128px));max-width:1800px;margin-inline:auto}.activities-hero{position:relative;isolation:isolate;overflow:hidden;background:#0a2948}.activities-hero>img{position:absolute;inset:0;z-index:-2;width:100%;height:100%;object-fit:cover}.activities-hero::after{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(100deg,#294e9ef5,#294e9edb 65%,#0a2948b8)}.hero-copy{padding-block:clamp(64px,7vw,112px)}.activities-eyebrow{font-size:12px;font-weight:700;letter-spacing:.18em;color:#ad8126;margin-bottom:20px}.hero-copy .activities-eyebrow{color:#f3cc48}.hero-copy h1{color:white;font-size:clamp(36px,5vw,74px);line-height:1.12;margin-bottom:24px;max-width:1100px}.hero-copy>p:last-child{max-width:950px;color:#edf2fa;font-size:clamp(17px,1.4vw,22px);line-height:1.8}.activities-section{padding-block:64px}.activities-page h2{font-size:clamp(30px,3.5vw,50px);color:#294e9e;line-height:1.15;margin-bottom:24px;max-width:900px}.section-lead{max-width:850px;color:#5d6e86;font-size:18px;line-height:1.8;margin-bottom:36px}.activity-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.activity-grid article,.benefit-grid article{overflow:hidden;border:1px solid #dde5f1;border-radius:6px;background:white;box-shadow:0 12px 30px #173a6a08;transition:transform .3s,box-shadow .3s}.activity-grid article:hover,.benefit-grid article:hover{transform:translateY(-4px);box-shadow:0 18px 38px #173a6a14}.activity-grid article>img{width:100%;aspect-ratio:1.8;object-fit:cover}.activity-copy{padding:28px}.activity-icon{display:grid;place-items:center;width:50px;height:50px;border-radius:50%;background:#fff8d8;color:#294e9e;margin-bottom:20px}.activities-page h3{font-size:21px;color:#0a2948;line-height:1.4;margin-bottom:14px}.activity-copy p,.benefit-grid p{color:#5d6e86;font-size:16px;line-height:1.8}.benefits-section{padding-block:64px;background:#fffbeb;border-block:1px solid #eee5ce}.benefit-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px;margin-top:36px}.benefit-grid article{padding:26px}.activity-gallery{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px;margin-top:32px}.activity-gallery img{width:100%;aspect-ratio:1.3;object-fit:cover;border-radius:6px}@media(max-width:1000px){.benefit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.activity-grid{grid-template-columns:1fr}.activity-gallery{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.activities-section,.benefits-section{padding-block:40px}}@media(max-width:420px){.benefit-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.activity-grid article,.benefit-grid article{transition:none}.activity-grid article:hover,.benefit-grid article:hover{transform:none}}
</style>
