<script setup>
import { ArrowRight } from 'lucide-vue-next'
import cover from '../assets/images/creative-4.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const copy = (en, bn) => language.value === 'bn' ? bn : en
const steps = [
  { title: ['Initial Consultation', 'প্রাথমিক আলোচনা'], body: ['Contact the PIISC admission office or arrange a campus visit. Discuss the appropriate grade, available seats, learning pathway, and current admission requirements for Grades 1–12.', 'পিআইআইএসসির ভর্তি অফিসে যোগাযোগ করুন অথবা ক্যাম্পাস পরিদর্শনের ব্যবস্থা করুন। প্রথম থেকে দ্বাদশ শ্রেণির উপযুক্ত শ্রেণি, আসনপ্রাপ্যতা, শিক্ষাক্রম ও বর্তমান ভর্তির শর্ত সম্পর্কে জানুন।'] },
  { title: ['Application Submission', 'আবেদন জমা'], body: ['Complete the admission application and prepare the supporting documents. Share accurate student and guardian details, previous school records, and the grade you wish to apply for.', 'ভর্তি আবেদন পূরণ করে প্রয়োজনীয় কাগজপত্র প্রস্তুত করুন। শিক্ষার্থী ও অভিভাবকের সঠিক তথ্য, পূর্ববর্তী শিক্ষাপ্রতিষ্ঠানের ফলাফল এবং কাঙ্ক্ষিত শ্রেণি উল্লেখ করুন।'] },
  { title: ['Student Readiness & Academic Review', 'শিক্ষার্থীর প্রস্তুতি ও শিক্ষাগত পর্যালোচনা'], body: ['The admission team will explain any assessment or interaction required for the chosen grade. Previous learning, academic records, and individual learning needs help guide placement.', 'নির্বাচিত শ্রেণির জন্য প্রয়োজনীয় মূল্যায়ন বা সাক্ষাৎকার সম্পর্কে ভর্তি অফিস জানাবে। পূর্ববর্তী শিক্ষা, ফলাফল ও ব্যক্তিগত শিক্ষার প্রয়োজন বিবেচনা করে শ্রেণি নির্ধারণ করা হবে।'] },
  { title: ['Parent Partnership Meeting', 'অভিভাবকের সঙ্গে আলোচনা'], body: ['Meet with the school to discuss your child’s interests, educational background, and support needs. This is also an opportunity to ask questions about school life and expectations.', 'আপনার সন্তানের আগ্রহ, শিক্ষাগত পটভূমি ও সহায়তার প্রয়োজন নিয়ে স্কুলের সঙ্গে আলোচনা করুন। স্কুলের দৈনন্দিন কার্যক্রম ও প্রত্যাশা সম্পর্কে প্রশ্ন করারও এটি একটি সুযোগ।'] },
  { title: ['Admission Decision', 'ভর্তির সিদ্ধান্ত'], body: ['The admission office will communicate the outcome after reviewing the application and available seats. If a place is offered, confirm the applicable fees, deadlines, and any remaining documents directly with the office.', 'আবেদন ও আসনপ্রাপ্যতা পর্যালোচনার পর ভর্তি অফিস সিদ্ধান্ত জানাবে। ভর্তির সুযোগ পেলে প্রযোজ্য ফি, সময়সীমা ও বাকি কাগজপত্র অফিস থেকে নিশ্চিত করুন।'] },
  { title: ['Enrollment & Orientation', 'ভর্তি সম্পন্ন ও পরিচিতি'], body: ['Complete the enrollment formalities and school-confirmed payments through the official channels. Ask the admission team about the class start date, learning materials, and orientation arrangements before your child joins.', 'নির্ধারিত মাধ্যমে ভর্তি প্রক্রিয়া ও স্কুল কর্তৃক নিশ্চিতকৃত অর্থ পরিশোধ সম্পন্ন করুন। ক্লাস শুরুর তারিখ, শিক্ষা উপকরণ ও পরিচিতি অনুষ্ঠানের ব্যবস্থা সম্পর্কে ভর্তি অফিস থেকে জেনে নিন।'] },
]
const stages = [
 { title: ['Primary · Grades 1–5', 'প্রাথমিক · প্রথম–পঞ্চম শ্রেণি'], body: ['Discuss foundational literacy, numeracy, communication, and readiness for the requested class.', 'মৌলিক ভাষা, গণনা, যোগাযোগ ও কাঙ্ক্ষিত শ্রেণির প্রস্তুতি নিয়ে আলোচনা করুন।'] },
 { title: ['Middle School · Grades 6–8', 'নিম্ন মাধ্যমিক · ষষ্ঠ–অষ্টম শ্রেণি'], body: ['Review previous progress and any grade-appropriate assessment advised by the school.', 'পূর্ববর্তী অগ্রগতি ও স্কুলের নির্দেশিত শ্রেণিভিত্তিক মূল্যায়ন সম্পর্কে জানুন।'] },
 { title: ['Secondary · Grades 9–10', 'মাধ্যমিক · নবম–দশম শ্রেণি'], body: ['Confirm subject choices, prior coursework, and any examination or transfer requirements.', 'বিষয় নির্বাচন, পূর্ববর্তী পাঠক্রম এবং পরীক্ষা বা স্থানান্তরের শর্ত নিশ্চিত করুন।'] },
 { title: ['College · Grades 11–12', 'কলেজ · একাদশ–দ্বাদশ শ্রেণি'], body: ['Discuss previous examination results, subject eligibility, registration, and entry or transfer conditions with the admission office.', 'পূর্ববর্তী পরীক্ষার ফলাফল, বিষয়ের যোগ্যতা, নিবন্ধন এবং ভর্তি বা স্থানান্তরের শর্ত নিয়ে ভর্তি অফিসে আলোচনা করুন।'] },
]
</script>
<template>
 <div class="procedures-page [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:initial] [&&]:[background-image:linear-gradient(rgb(255,_255,_255),_rgb(249,_250,_255))] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(10,_41,_72)]">
  <section class="procedures-hero [&&]:relative [&&]:isolate [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&.procedures-hero::after]:absolute [&.procedures-hero::after]:bottom-[0px] [&.procedures-hero::after]:left-[0px] [&.procedures-hero::after]:right-[0px] [&.procedures-hero::after]:top-[0px] [&.procedures-hero::after]:z-[-1] [&.procedures-hero::after]:[background-attachment:initial] [&.procedures-hero::after]:[background-clip:initial] [&.procedures-hero::after]:[background-color:initial] [&.procedures-hero::after]:[background-image:linear-gradient(100deg,_rgba(41,_78,_158,_0.96),_rgba(41,_78,_158,_0.86)_65%,_rgba(10,_41,_72,_0.737))] [&.procedures-hero::after]:[background-origin:initial] [&.procedures-hero::after]:[background-position:initial] [&.procedures-hero::after]:[background-repeat:initial] [&.procedures-hero::after]:[background-size:initial] [&.procedures-hero::after]:[content:'']" aria-labelledby="procedures-title">
   <img class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:z-[-2] [&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [&&]:[object-position:center_40%]" :src="cover" :alt="copy('Learning activities at PIISC', 'পিআইআইএসসির শিক্ষামূলক কার্যক্রম')" fetchpriority="high" />
   <div class="procedures-width hero-copy [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:700px)]:[&&]:[padding-block-end:64px] [@media(width>700px)]:[&&]:[padding-block-end:clamp(64px,_7vw,_112px)] [@media(max-width:700px)]:[&&]:[padding-block-start:56px] [@media(width>700px)]:[&&]:[padding-block-start:clamp(64px,_7vw,_112px)]">
    <p class="eyebrow [&&&]:mb-[24px] [&&&]:[color:rgb(243,_204,_72)] [.hero-copy>p&:last-child]:[color:rgb(237,_242,_250)] [.hero-copy>p&:last-child]:[font-size:clamp(17px,_1.5vw,_23px)] [.hero-copy>p&:last-child]:max-w-[1100px] [.hero-copy>p&:last-child]:leading-[1.75]">{{ copy('ADMISSION', 'ভর্তি') }}</p>
    <h1 class="[&&]:[font-size:clamp(36px,_5vw,_78px)] [&&]:leading-[1.12] [&&]:[color:rgb(255,_255,_255)] [&&]:m-[0px_0px_28px_0px]" id="procedures-title">{{ copy('Admission Procedures', 'ভর্তি প্রক্রিয়া') }}</h1>
    <p class="[.hero-copy>p&:last-child]:[font-size:clamp(17px,_1.5vw,_23px)] [.hero-copy>p&:last-child]:max-w-[1100px] [.hero-copy>p&:last-child]:leading-[1.75] [.hero-copy>p&:last-child]:[color:rgb(237,_242,_250)]">{{ copy('Your six-step guide to joining PIISC, from the first conversation to enrollment in Grades 1–12.', 'প্রথম আলোচনা থেকে প্রথম–দ্বাদশ শ্রেণিতে ভর্তি পর্যন্ত পিআইআইএসসিতে যোগ দেওয়ার ছয় ধাপের নির্দেশনা।') }}</p>
   </div>
  </section>
  <div class="procedures-width procedures-content [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:700px)]:[&&]:[padding-block-end:44px] [@media(width>700px)]:[&&]:[padding-block-end:64px] [@media(max-width:700px)]:[&&]:[padding-block-start:32px] [@media(width>700px)]:[&&]:[padding-block-start:48px]">
   <ol class="procedure-list [&&]:grid [&&]:gap-x-[20px] [&&]:gap-y-[20px] [&&]:[list-style-image:initial] [&&]:[list-style-position:initial] [&&]:[list-style-type:none] [&&]:m-[0px] [&&]:p-[0px]">
    <li v-for="(step, index) in steps" :key="step.title[0]" class="procedure-card [&&]:grid [@media(max-width:420px)]:[&&]:grid-cols-[1fr] [@media(width>420px)]:[&&]:grid-cols-[auto_minmax(0px,_1fr)] [@media(max-width:700px)]:[&&]:gap-x-[14px] [@media(width>700px)]:[&&]:gap-x-[22px] [@media(max-width:700px)]:[&&]:gap-y-[14px] [@media(width>700px)]:[&&]:gap-y-[22px] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[box-shadow:rgba(23,_58,_106,_0.02)_0px_12px_32px] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.3s,_0.3s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:border-color,_box-shadow] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [@media(max-width:700px)]:[&&]:p-[20px_16px] [@media(width>700px)]:[&&]:p-[clamp(22px,_2.2vw,_36px)] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_228,_241)] [&.procedure-card:hover]:[box-shadow:rgba(23,_58,_106,_0.063)_0px_16px_38px] [&.procedure-card:hover]:[border-color:rgb(201,_173,_98)]">
     <span class="step-number [&&]:grid [@media(max-width:700px)]:[&&]:h-[42px] [@media(width>700px)]:[&&]:h-[64px] [@media(max-width:700px)]:[&&]:w-[42px] [@media(width>700px)]:[&&]:w-[64px] [&&]:items-center [&&]:[justify-items:center] [&&]:[border-bottom-left-radius:50%] [&&]:[border-bottom-right-radius:50%] [&&]:[border-top-left-radius:50%] [&&]:[border-top-right-radius:50%] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(41,_78,_158)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(255,_255,_255)] [@media(max-width:700px)]:[&&]:[font-size:18px] [@media(width>700px)]:[&&]:[font-size:22px] [&&]:font-[700]" aria-hidden="true">{{ new Intl.NumberFormat(language === 'bn' ? 'bn-BD' : 'en').format(index + 1) }}</span>
     <div class="step-copy">
      <h2 class="[@media(max-width:700px)]:[&&]:[font-size:21px] [@media(width>700px)]:[&&]:[font-size:clamp(22px,_1.9vw,_29px)] [&&]:leading-[1.35] [&&]:[color:rgb(41,_78,_158)] [&&]:m-[0px_0px_14px_0px]">{{ copy(...step.title) }}</h2>
      <p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:clamp(16px,_1.25vw,_20px)] [&&]:leading-[1.8] [&&]:m-[0px]">{{ copy(...step.body) }}</p>
      <div v-if="index === 2" class="assessment-grid [&&]:mt-[24px] [&&]:grid [@media(max-width:700px)]:[&&]:grid-cols-[1fr] [@media(width>700px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [&&]:gap-x-[16px] [&&]:gap-y-[16px]">
       <section class="[&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(252,_245,_230)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:p-[22px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(228,_223,_211)]" v-for="stage in stages" :key="stage.title[0]"><h3 class="[&&]:[font-size:18px] [&&]:leading-[1.45] [&&]:[color:rgb(41,_78,_158)] [&&]:m-[0px_0px_12px_0px]">{{ copy(...stage.title) }}</h3><p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:16px] [&&]:leading-[1.8] [&&]:m-[0px]">{{ copy(...stage.body) }}</p></section>
      </div>
     </div>
    </li>
   </ol>
   <RouterLink to="/online-admission" class="application-button [&&]:mt-[36px] [&&]:inline-flex [&&]:cursor-pointer [&&]:items-center [&&]:gap-x-[12px] [&&]:gap-y-[12px] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:font-[700] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(41,_78,_158)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(255,_255,_255)] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.25s,_0.25s,_0.25s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:transform,_background,_box-shadow] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [@media(max-width:420px)]:[&&]:w-[100%] [@media(max-width:420px)]:[&&]:justify-center [&&]:p-[16px_22px] [&.application-button:hover]:[background-color:rgb(10,_41,_72)] [&.application-button:hover]:[box-shadow:rgba(23,_58,_106,_0.125)_0px_12px_26px] [@media(prefers-reduced-motion:no-preference)]:[&.application-button:hover]:[transform:translateY(-3px)] [@media(prefers-reduced-motion:reduce)]:[&.application-button:hover]:[transform:none]">{{ copy('Start Your Application', 'আপনার আবেদন শুরু করুন') }}<ArrowRight :size="20" aria-hidden="true" /></RouterLink>
  </div>
 </div>
</template>
