<script setup>
import { ArrowRight, CircleCheck } from 'lucide-vue-next'
import cover from '../assets/images/orientation.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const copy = (en, bn) => language.value === 'bn' ? bn : en
const grades = Array.from({length:12},(_,index)=>({grade:index+1,age:index+6}))
const number = value => new Intl.NumberFormat(language.value === 'bn' ? 'bn-BD' : 'en').format(value)
const documents = [
 ['Completed admission application form','পূরণকৃত ভর্তি আবেদন ফরম'],
 ['Copy of the student’s birth certificate or passport','শিক্ষার্থীর জন্মনিবন্ধন বা পাসপোর্টের কপি'],
 ['Recent passport-size photographs of the student','শিক্ষার্থীর সাম্প্রতিক পাসপোর্ট আকারের ছবি'],
 ['Passport-size photograph of the parent or guardian','অভিভাবকের পাসপোর্ট আকারের ছবি'],
 ['Copy of the parent or guardian’s National ID','অভিভাবকের জাতীয় পরিচয়পত্রের কপি'],
 ['Previous academic report or transcript, where applicable','প্রযোজ্য ক্ষেত্রে পূর্ববর্তী শিক্ষাপ্রতিষ্ঠানের ফলাফল বা নম্বরপত্র'],
 ['School leaving or transfer certificate, for transfer students','স্থানান্তরিত শিক্ষার্থীদের জন্য ছাড়পত্র'],
 ['For college entry: previous examination results and registration documents, as applicable','কলেজে ভর্তির জন্য প্রযোজ্য পূর্ববর্তী পরীক্ষার ফলাফল ও নিবন্ধনের কাগজপত্র'],
]
</script>
<template>
 <div class="requirements-page [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(10,_41,_72)]">
  <section class="requirements-hero [&&]:relative [&&]:isolate [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&.requirements-hero::after]:absolute [&.requirements-hero::after]:bottom-[0px] [&.requirements-hero::after]:left-[0px] [&.requirements-hero::after]:right-[0px] [&.requirements-hero::after]:top-[0px] [&.requirements-hero::after]:z-[-1] [&.requirements-hero::after]:[background-attachment:initial] [&.requirements-hero::after]:[background-clip:initial] [&.requirements-hero::after]:[background-color:initial] [&.requirements-hero::after]:[background-image:linear-gradient(100deg,_rgba(41,_78,_158,_0.96),_rgba(41,_78,_158,_0.86)_65%,_rgba(10,_41,_72,_0.737))] [&.requirements-hero::after]:[background-origin:initial] [&.requirements-hero::after]:[background-position:initial] [&.requirements-hero::after]:[background-repeat:initial] [&.requirements-hero::after]:[background-size:initial] [&.requirements-hero::after]:[content:'']" aria-labelledby="eligibility-title">
   <img class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:z-[-2] [&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [&&]:[object-position:center_40%]" :src="cover" :alt="copy('PIISC school orientation programme','পিআইআইএসসির পরিচিতি অনুষ্ঠান')" fetchpriority="high" />
   <div class="requirements-width hero-copy [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [&&]:[padding-block-end:clamp(64px,_7vw,_112px)] [&&]:[padding-block-start:clamp(64px,_7vw,_112px)]">
    <p class="requirements-eyebrow [&&&]:[color:rgb(243,_204,_72)] [&&&]:[font-size:13px] [&&&]:font-[700] [&&&]:tracking-[0.18em] [&&&]:m-[0px_0px_20px_0px] [.hero-copy>p&:last-child]:[color:rgb(237,_242,_250)] [.hero-copy>p&:last-child]:[font-size:clamp(17px,_1.4vw,_22px)] [.hero-copy>p&:last-child]:max-w-[920px] [.hero-copy>p&:last-child]:leading-[1.8]">{{ copy('ADMISSION','ভর্তি') }}</p>
    <h1 class="[&&]:[color:rgb(255,_255,_255)] [&&]:[font-size:clamp(36px,_5vw,_76px)] [&&]:leading-[1.12] [&&]:m-[0px_0px_26px_0px]" id="eligibility-title">{{ copy('Eligibility for Admission','ভর্তির যোগ্যতা') }}</h1>
    <p class="[.hero-copy>p&:last-child]:[color:rgb(237,_242,_250)] [.hero-copy>p&:last-child]:[font-size:clamp(17px,_1.4vw,_22px)] [.hero-copy>p&:last-child]:max-w-[920px] [.hero-copy>p&:last-child]:leading-[1.8]">{{ copy('Explore admission to PIISC from Grade 1 through Grade 12. Placement is subject to seat availability, previous academic records, and completion of the admission process.','প্রথম থেকে দ্বাদশ শ্রেণি পর্যন্ত পিআইআইএসসিতে ভর্তির তথ্য জানুন। আসনপ্রাপ্যতা, পূর্ববর্তী শিক্ষাগত ফলাফল ও ভর্তি প্রক্রিয়া সম্পন্ন করার ভিত্তিতে শ্রেণি নির্ধারিত হয়।') }}</p>
   </div>
  </section>
  <section class="requirements-width age-section [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:540px)]:[&&]:[padding-block-end:40px] [@media(width>540px)]:[&&]:[padding-block-end:60px] [@media(max-width:540px)]:[&&]:[padding-block-start:40px] [@media(width>540px)]:[&&]:[padding-block-start:60px]" aria-labelledby="class-title">
   <p class="requirements-eyebrow [&&]:[color:rgb(178,_138,_41)] [&&]:[font-size:13px] [&&]:font-[700] [&&]:tracking-[0.18em] [&&]:m-[0px_0px_20px_0px]">{{ copy('CLASS & AGE GUIDANCE','শ্রেণি ও বয়সের নির্দেশনা') }}</p>
   <h2 class="[&&]:[font-size:clamp(30px,_3.4vw,_52px)] [&&]:leading-[1.15] [&&]:[color:rgb(41,_78,_158)] [&&]:m-[0px_0px_34px_0px]" id="class-title">{{ copy('Find the right class for your child.','আপনার সন্তানের জন্য উপযুক্ত শ্রেণি বেছে নিন।') }}</h2>
   <div class="table-frame [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:overflow-x-auto [&&]:overflow-y-auto [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[box-shadow:rgba(23,_58,_106,_0.03)_0px_16px_40px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_228,_241)]" role="region" :aria-label="copy('Class and age guidance table','শ্রেণি ও বয়সের নির্দেশনা সারণি')" tabindex="0">
    <table class="[&&]:w-[100%] [&&]:text-left [&&]:[border-collapse:collapse] [&&]:[font-size:clamp(13px,_1vw,_16px)] [@media(max-width:540px)]:[&&]:min-w-[440px]" aria-describedby="age-note">
     <thead class="[&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(8,_38,_80)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(255,_255,_255)]"><tr><th class="[&&]:leading-[1.45] [&&]:w-[33.333%] [&&]:font-[700] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]" scope="col">{{ copy('Grade','শ্রেণি') }}</th><th class="[&&]:leading-[1.45] [&&]:w-[33.333%] [&&]:font-[700] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]" scope="col">{{ copy('Learning stage','শিক্ষার পর্যায়') }}</th><th class="[&&]:leading-[1.45] [&&]:w-[33.333%] [&&]:font-[700] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]" scope="col">{{ copy('Typical age range','সাধারণ বয়সসীমা') }}</th></tr></thead>
     <tbody><tr class="[&&]:[border-top-color:rgb(220,_228,_241)] [&&]:[border-top-style:solid] [&&]:[border-top-width:1px] [&&]:[color:rgb(93,_110,_134)] [&&]:[transition-behavior:normal] [&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.2s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:background] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [&&]:[transition-timing-function:ease] [tbody_tr&:nth-child(even)]:[background-attachment:initial] [tbody_tr&:nth-child(even)]:[background-clip:initial] [tbody_tr&:nth-child(even)]:[background-color:rgb(252,_248,_240)] [tbody_tr&:nth-child(even)]:[background-image:initial] [tbody_tr&:nth-child(even)]:[background-origin:initial] [tbody_tr&:nth-child(even)]:[background-position:initial] [tbody_tr&:nth-child(even)]:[background-repeat:initial] [tbody_tr&:nth-child(even)]:[background-size:initial] [tbody_tr&:hover]:[background-attachment:initial] [tbody_tr&:hover]:[background-clip:initial] [tbody_tr&:hover]:[background-color:rgb(237,_242,_251)] [tbody_tr&:hover]:[background-image:initial] [tbody_tr&:hover]:[background-origin:initial] [tbody_tr&:hover]:[background-position:initial] [tbody_tr&:hover]:[background-repeat:initial] [tbody_tr&:hover]:[background-size:initial]" v-for="item in grades" :key="item.grade"><th class="[&&]:leading-[1.45] [&&]:font-[400] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]" scope="row">{{ copy('Grade','শ্রেণি') }} {{ number(item.grade) }}</th><td class="[&&]:leading-[1.45] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]">{{ item.grade <= 5 ? copy('Primary school','প্রাথমিক') : item.grade <= 8 ? copy('Middle school','নিম্ন মাধ্যমিক') : item.grade <= 10 ? copy('Secondary school','মাধ্যমিক') : copy('Higher secondary / College','উচ্চ মাধ্যমিক / কলেজ') }}</td><td class="[&&]:leading-[1.45] [@media(max-width:540px)]:[&&]:p-[10px_12px] [@media(width>540px)]:[&&]:p-[12px_20px]">{{ number(item.age) }}–{{ number(item.age + 1) }} {{ copy('years','বছর') }}</td></tr></tbody>
    </table>
   </div>
   <p id="age-note" class="age-note [&&]:[color:rgb(103,_118,_139)] [&&]:[font-size:14px] [&&]:mt-[20px] [&&]:max-w-[1100px] [&&]:leading-[1.8]">{{ copy('These ages are general guidance, not fixed PIISC eligibility rules. Please confirm the age cut-off, class placement, subject choices, and Grade 11–12 entry or transfer requirements with the admission office.','এই বয়সসীমা সাধারণ নির্দেশনা, পিআইআইএসসির নির্দিষ্ট ভর্তির নিয়ম নয়। বয়স নির্ধারণের তারিখ, শ্রেণি নির্বাচন, বিষয় এবং একাদশ–দ্বাদশ শ্রেণিতে ভর্তি বা স্থানান্তরের শর্ত ভর্তি অফিস থেকে নিশ্চিত করুন।') }}</p>
  </section>
  <section class="requirements-width documents-section [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [&&]:grid [@media(max-width:900px)]:[&&]:grid-cols-[1fr] [@media(width>900px)]:[&&]:grid-cols-[0.85fr_1.15fr] [@media(max-width:900px)]:[&&]:gap-x-[28px] [@media(width>900px)]:[&&]:gap-x-[60px] [@media(max-width:900px)]:[&&]:gap-y-[28px] [@media(width>900px)]:[&&]:gap-y-[36px] [&&]:[padding-block-end:70px] [&&]:[padding-block-start:10px] [@media(max-width:540px)]:[&&]:pb-[44px]" aria-labelledby="documents-title">
   <div class="documents-copy [@media(max-width:900px)]:[&&]:max-w-[700px] [@media(width>900px)]:[&&]:max-w-[510px]">
    <p class="requirements-eyebrow [&&]:[color:rgb(178,_138,_41)] [&&]:[font-size:13px] [&&]:font-[700] [&&]:tracking-[0.18em] [&&]:m-[0px_0px_20px_0px] [.documents-copy>p&:last-child]:[color:rgb(93,_110,_134)] [.documents-copy>p&:last-child]:[font-size:18px] [.documents-copy>p&:last-child]:leading-[1.8]">{{ copy('REQUIRED DOCUMENTS','প্রয়োজনীয় কাগজপত্র') }}</p>
    <h2 class="[&&]:[font-size:clamp(30px,_3.4vw,_52px)] [&&]:leading-[1.15] [&&]:[color:rgb(41,_78,_158)] [&&]:m-[0px_0px_34px_0px]" id="documents-title">{{ copy('Ready your paperwork in advance.','আগেই প্রস্তুত রাখুন প্রয়োজনীয় কাগজপত্র।') }}</h2>
    <p class="[.documents-copy>p&:last-child]:[color:rgb(93,_110,_134)] [.documents-copy>p&:last-child]:[font-size:18px] [.documents-copy>p&:last-child]:leading-[1.8]">{{ copy('Prepare the following documents for your application. The admission team will confirm the final requirements and number of copies for your child’s grade.','আবেদনের জন্য নিচের কাগজপত্র প্রস্তুত রাখুন। আপনার সন্তানের শ্রেণি অনুযায়ী চূড়ান্ত তালিকা ও কপির সংখ্যা ভর্তি অফিস নিশ্চিত করবে।') }}</p>
   </div>
   <ul class="document-grid [&&]:grid [@media(max-width:540px)]:[&&]:grid-cols-[1fr] [@media(width>540px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [&&]:gap-x-[16px] [&&]:gap-y-[16px] [&&]:[list-style-image:initial] [&&]:[list-style-position:initial] [&&]:[list-style-type:none] [&&]:m-[0px] [&&]:p-[0px]"><li class="[&&]:flex [&&]:items-start [&&]:gap-x-[16px] [&&]:gap-y-[16px] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[box-shadow:rgba(23,_58,_106,_0.024)_0px_12px_30px] [&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:16px] [&&]:leading-[1.8] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.25s,_0.25s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:box-shadow,_border-color] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [&&]:p-[24px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(221,_229,_241)] [.document-grid_li&:hover]:[box-shadow:rgba(23,_58,_106,_0.07)_0px_15px_32px] [.document-grid_li&:hover]:[border-color:rgb(217,_179,_61)]" v-for="item in documents" :key="item[0]"><CircleCheck class="[&&]:mt-[3px] [&&]:[flex-shrink:0] [&&]:[color:rgb(41,_78,_158)]" :size="22" aria-hidden="true"/><span>{{ copy(...item) }}</span></li></ul>
   <RouterLink to="/application-process" class="procedure-button [&&]:[grid-column-end:-1] [&&]:[grid-column-start:1] [&&]:inline-flex [&&]:cursor-pointer [&&]:items-center [&&]:gap-x-[14px] [&&]:gap-y-[14px] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:font-[700] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(41,_78,_158)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:white] [&&]:[justify-self:start] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.25s,_0.25s,_0.25s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:transform,_background,_box-shadow] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [@media(max-width:540px)]:[&&]:w-[100%] [@media(max-width:540px)]:[&&]:justify-center [&&]:p-[16px_22px] [&.procedure-button:hover]:[background-color:rgb(10,_41,_72)] [&.procedure-button:hover]:[box-shadow:rgba(23,_58,_106,_0.14)_0px_12px_24px] [@media(prefers-reduced-motion:no-preference)]:[&.procedure-button:hover]:[transform:translateY(-3px)] [@media(prefers-reduced-motion:reduce)]:[&.procedure-button:hover]:[transform:none]">{{ copy('View Admission Procedures','ভর্তি প্রক্রিয়া দেখুন') }}<ArrowRight :size="21" aria-hidden="true"/></RouterLink>
  </section>
 </div>
</template>
