<script setup>
import { Clock3, Facebook, Mail, MapPin, MessageCircle, Phone } from 'lucide-vue-next'
import { address, schoolMapUrl } from '../data/content.js'
import { headerContacts } from '../data/navigation.js'
import { useI18n } from '../composables/useI18n.js'
import ContactForm from '../components/ContactForm.vue'
import coverPhoto from '../assets/images/studytime.jpg'

const { language } = useI18n()
const copy = (en, bn) => language.value === 'bn' ? bn : en
const phone = headerContacts.phone.trim()
const phoneUrl = `tel:${phone.replace(/\s/g, '')}`
const whatsappUrl = `https://wa.me/${phone.replace(/\D/g, '')}`
const mapUrl = schoolMapUrl
</script>

<template>
  <main>
    <section class="contact-hero [&&]:flex [@media(max-width:600px)]:[&&]:min-h-[320px] [@media(width>600px)]:[&&]:min-h-[390px] [&&]:items-center [&&]:[background-image:linear-gradient(90deg,#294e9ef2_0%,#294e9ee8_52%,#294e9eb8_100%),var(--cover-photo)] [&&]:[color:white] [&&]:[background-size:cover] [&&]:[background-position:center_center]" :style="{ '--cover-photo': `url(${coverPhoto})` }" aria-labelledby="contact-title"><div class="contact-width [&&&]:max-w-[1350px] [&&&]:[margin-inline-end:auto] [&&&]:[margin-inline-start:auto] [&&&]:w-[calc(100%_-_clamp(36px,_6.5vw,_130px))] [@media(max-width:600px)]:[&&&]:[padding-block-end:46px] [@media(width>600px)]:[&&&]:[padding-block-end:58px] [@media(max-width:600px)]:[&&&]:[padding-block-start:46px] [@media(width>600px)]:[&&&]:[padding-block-start:58px]"><p class="hero-label [&&]:tracking-[0.18em] [&&]:[font-size:12px] [&&]:mb-[16px] [&&]:font-[800] [&&]:[color:rgb(245,_205,_70)] [@media(max-width:600px)]:[.contact-hero_p&:last-child]:[font-size:16px] [@media(width>600px)]:[.contact-hero_p&:last-child]:[font-size:18px] [.contact-hero_p&:last-child]:[color:rgb(243,_246,_255)] [.contact-hero_p&:last-child]:max-w-[660px] [.contact-hero_p&:last-child]:leading-[1.7]">{{ copy('CONTACT', 'যোগাযোগ') }}</p><h1 class="[&&]:[font-size:clamp(44px,_5.6vw,_78px)] [&&]:max-w-[930px] [&&]:leading-[1.04] [&&]:[color:white] [&&]:m-[0px_0px_22px_0px]" id="contact-title">{{ copy('Connect with the PIISC admission office.', 'পিআইআইএসসির ভর্তি বিভাগে যোগাযোগ করুন।') }}</h1><p class="[@media(max-width:600px)]:[.contact-hero_p&:last-child]:[font-size:16px] [@media(width>600px)]:[.contact-hero_p&:last-child]:[font-size:18px] [.contact-hero_p&:last-child]:max-w-[660px] [.contact-hero_p&:last-child]:leading-[1.7] [.contact-hero_p&:last-child]:[color:rgb(243,_246,_255)]">{{ copy('Send an inquiry, request a callback, call the office, or reach the school through WhatsApp and email.', 'অনুসন্ধান পাঠান, ফোনকলের অনুরোধ করুন, অথবা ফোন, হোয়াটসঅ্যাপ ও ইমেইলে যোগাযোগ করুন।') }}</p></div></section>
    <section class="contact-section [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [@media(max-width:600px)]:[&&]:p-[48px_0px_65px_0px] [@media(width>600px)]:[&&]:p-[70px_0px_90px_0px]"><div class="contact-width contact-layout [&&]:max-w-[1350px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(36px,_6.5vw,_130px))] [&&]:grid [@media(max-width:1000px)]:[&&]:grid-cols-[1fr] [@media(width>1000px)]:[&&]:grid-cols-[minmax(0px,_0.87fr)_minmax(0px,_1.13fr)] [&&]:[align-items:start] [@media(max-width:1000px)]:[&&]:gap-x-[40px] [@media(width>1000px)]:[&&]:gap-x-[clamp(38px,_5vw,_75px)] [@media(max-width:1000px)]:[&&]:gap-y-[40px] [@media(width>1000px)]:[&&]:gap-y-[clamp(38px,_5vw,_75px)]">
      <div class="contact-copy [@media(max-width:1000px)]:[&&]:max-w-[750px]"><p class="section-label [&&&]:tracking-[0.18em] [&&&]:[font-size:11px] [&&&]:mb-[10px] [&&&]:font-[800] [&&&]:[color:rgb(190,_146,_40)]">{{ copy('CONTACT', 'যোগাযোগ') }}</p><h2 class="[&&]:[font-size:clamp(38px,_3.7vw,_50px)] [&&]:max-w-[440px] [&&]:leading-[1.08] [&&]:[color:rgb(41,_78,_158)] [&&]:m-[0px_0px_14px_0px]">{{ copy('Reach the school office.', 'বিদ্যালয় অফিসে যোগাযোগ করুন।') }}</h2><p class="intro [&&&]:[font-size:15px] [&&&]:mb-[22px] [&&&]:max-w-[420px] [&&&]:leading-[1.75] [&&&]:[color:rgb(82,_102,_132)]">{{ copy('Contact the admissions desk for details about class placement, admission, and visiting hours.', 'শ্রেণি নির্বাচন, ভর্তি ও পরিদর্শনের সময় সম্পর্কে জানতে ভর্তি বিভাগে যোগাযোগ করুন।') }}</p>
        <div class="contact-methods [&&&]:grid [&&&]:gap-x-[12px] [&&&]:gap-y-[12px] [&&&]:max-w-[500px]">
          <a class="[&&&]:flex [@media(max-width:600px)]:[&&&]:min-h-[70px] [@media(width>600px)]:[&&&]:min-h-[74px] [&&&]:items-center [&&&]:gap-x-[13px] [&&&]:gap-y-[13px] [&&&]:[border-image-outset:0] [&&&]:[border-image-repeat:stretch] [&&&]:[border-image-slice:100%] [&&&]:[border-image-source:none] [&&&]:[border-image-width:1] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(255,_255,_255)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(23,_34,_56)] [&&&]:p-[12px] [&&&]:[border-width:1px] [&&&]:[border-style:solid] [&&&]:[border-color:rgb(220,_177,_59)] [.contact-methods>a&:hover]:[background-color:rgb(255,_253,_245)] [.contact-methods>a&:hover]:[border-color:rgb(41,_78,_158)]" :href="phoneUrl"><span class="method-icon [&&&]:grid [&&&]:h-[48px] [&&&]:w-[48px] [&&&]:items-center [&&&]:[justify-items:center] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(50,_133,_231)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(255,_224,_65)] [&&&]:[flex-basis:auto] [&&&]:[flex-grow:0] [&&&]:[flex-shrink:0]"><Phone class="[&&&]:h-[24px] [&&&]:w-[24px]" aria-hidden="true" /></span><strong class="[@media(max-width:600px)]:[&&&]:[font-size:15px] [@media(width>600px)]:[&&&]:[font-size:16px] [&&&]:leading-[1.35] [&&&]:[overflow-wrap:anywhere] [&&&]:font-[800]">{{ phone }}</strong></a>
          <a class="[&&&]:flex [@media(max-width:600px)]:[&&&]:min-h-[70px] [@media(width>600px)]:[&&&]:min-h-[74px] [&&&]:items-center [&&&]:gap-x-[13px] [&&&]:gap-y-[13px] [&&&]:[border-image-outset:0] [&&&]:[border-image-repeat:stretch] [&&&]:[border-image-slice:100%] [&&&]:[border-image-source:none] [&&&]:[border-image-width:1] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(255,_255,_255)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(23,_34,_56)] [&&&]:p-[12px] [&&&]:[border-width:1px] [&&&]:[border-style:solid] [&&&]:[border-color:rgb(220,_177,_59)] [.contact-methods>a&:hover]:[background-color:rgb(255,_253,_245)] [.contact-methods>a&:hover]:[border-color:rgb(41,_78,_158)]" :href="`mailto:${headerContacts.email}`"><span class="method-icon [&&&]:grid [&&&]:h-[48px] [&&&]:w-[48px] [&&&]:items-center [&&&]:[justify-items:center] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(50,_133,_231)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(255,_224,_65)] [&&&]:[flex-basis:auto] [&&&]:[flex-grow:0] [&&&]:[flex-shrink:0]"><Mail class="[&&&]:h-[24px] [&&&]:w-[24px]" aria-hidden="true" /></span><strong class="[@media(max-width:600px)]:[&&&]:[font-size:15px] [@media(width>600px)]:[&&&]:[font-size:16px] [&&&]:leading-[1.35] [&&&]:[overflow-wrap:anywhere] [&&&]:font-[800]">{{ headerContacts.email }}</strong></a>
          <a class="[&&&]:flex [@media(max-width:600px)]:[&&&]:min-h-[70px] [@media(width>600px)]:[&&&]:min-h-[74px] [&&&]:items-center [&&&]:gap-x-[13px] [&&&]:gap-y-[13px] [&&&]:[border-image-outset:0] [&&&]:[border-image-repeat:stretch] [&&&]:[border-image-slice:100%] [&&&]:[border-image-source:none] [&&&]:[border-image-width:1] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(255,_255,_255)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(23,_34,_56)] [&&&]:p-[12px] [&&&]:[border-width:1px] [&&&]:[border-style:solid] [&&&]:[border-color:rgb(220,_177,_59)] [.contact-methods>a&:hover]:[background-color:rgb(255,_253,_245)] [.contact-methods>a&:hover]:[border-color:rgb(41,_78,_158)]" :href="whatsappUrl" target="_blank" rel="noopener noreferrer"><span class="method-icon [&&&]:grid [&&&]:h-[48px] [&&&]:w-[48px] [&&&]:items-center [&&&]:[justify-items:center] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(50,_133,_231)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(255,_224,_65)] [&&&]:[flex-basis:auto] [&&&]:[flex-grow:0] [&&&]:[flex-shrink:0]"><MessageCircle class="[&&&]:h-[24px] [&&&]:w-[24px]" aria-hidden="true" /></span><strong class="[@media(max-width:600px)]:[&&&]:[font-size:15px] [@media(width>600px)]:[&&&]:[font-size:16px] [&&&]:leading-[1.35] [&&&]:[overflow-wrap:anywhere] [&&&]:font-[800]">{{ copy('WhatsApp admission support', 'হোয়াটসঅ্যাপে ভর্তি সহায়তা') }}</strong></a>
          <a class="[&&&]:flex [@media(max-width:600px)]:[&&&]:min-h-[70px] [@media(width>600px)]:[&&&]:min-h-[74px] [&&&]:items-center [&&&]:gap-x-[13px] [&&&]:gap-y-[13px] [&&&]:[border-image-outset:0] [&&&]:[border-image-repeat:stretch] [&&&]:[border-image-slice:100%] [&&&]:[border-image-source:none] [&&&]:[border-image-width:1] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(255,_255,_255)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(23,_34,_56)] [&&&]:p-[12px] [&&&]:[border-width:1px] [&&&]:[border-style:solid] [&&&]:[border-color:rgb(220,_177,_59)] [.contact-methods>a&:hover]:[background-color:rgb(255,_253,_245)] [.contact-methods>a&:hover]:[border-color:rgb(41,_78,_158)]" :href="mapUrl" target="_blank" rel="noopener noreferrer"><span class="method-icon [&&&]:grid [&&&]:h-[48px] [&&&]:w-[48px] [&&&]:items-center [&&&]:[justify-items:center] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(50,_133,_231)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(255,_224,_65)] [&&&]:[flex-basis:auto] [&&&]:[flex-grow:0] [&&&]:[flex-shrink:0]"><MapPin class="[&&&]:h-[24px] [&&&]:w-[24px]" aria-hidden="true" /></span><strong class="[@media(max-width:600px)]:[&&&]:[font-size:15px] [@media(width>600px)]:[&&&]:[font-size:16px] [&&&]:leading-[1.35] [&&&]:[overflow-wrap:anywhere] [&&&]:font-[800]">{{ copy(address, 'দ্য হোয়াইট প্যালেস ইউনিক, ১৩৪৯ ঢাকা–আশুলিয়া মহাসড়ক, বাইপাইল') }}</strong></a>
          <div class="office-hours [&&&]:flex [@media(max-width:600px)]:[&&&]:min-h-[70px] [@media(width>600px)]:[&&&]:min-h-[74px] [&&&]:items-center [&&&]:gap-x-[13px] [&&&]:gap-y-[13px] [&&&]:[border-image-outset:0] [&&&]:[border-image-repeat:stretch] [&&&]:[border-image-slice:100%] [&&&]:[border-image-source:none] [&&&]:[border-image-width:1] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(255,_255,_255)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(23,_34,_56)] [&&&]:p-[12px] [&&&]:[border-width:1px] [&&&]:[border-style:solid] [&&&]:[border-color:rgb(220,_177,_59)]"><span class="method-icon [&&&]:grid [&&&]:h-[48px] [&&&]:w-[48px] [&&&]:items-center [&&&]:[justify-items:center] [&&&]:[border-bottom-left-radius:6px] [&&&]:[border-bottom-right-radius:6px] [&&&]:[border-top-left-radius:6px] [&&&]:[border-top-right-radius:6px] [&&&]:[background-attachment:initial] [&&&]:[background-clip:initial] [&&&]:[background-color:rgb(50,_133,_231)] [&&&]:[background-image:initial] [&&&]:[background-origin:initial] [&&&]:[background-position:initial] [&&&]:[background-repeat:initial] [&&&]:[background-size:initial] [&&&]:[color:rgb(255,_224,_65)] [&&&]:[flex-basis:auto] [&&&]:[flex-grow:0] [&&&]:[flex-shrink:0]"><Clock3 class="[&&&]:h-[24px] [&&&]:w-[24px]" aria-hidden="true" /></span><strong class="[@media(max-width:600px)]:[&&&]:[font-size:15px] [@media(width>600px)]:[&&&]:[font-size:16px] [&&&]:leading-[1.35] [&&&]:[overflow-wrap:anywhere] [&&&]:font-[800]">{{ copy('Call to confirm office hours before visiting.', 'পরিদর্শনের আগে ফোন করে অফিসের সময় নিশ্চিত করুন।') }}</strong></div>
        </div>
        <a v-if="headerContacts.socials.facebook" class="facebook-link [&&]:mt-[16px] [&&]:h-[34px] [&&]:w-[34px] [&&]:items-center [&&]:[justify-items:center] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[display:inline-grid] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[color:rgb(41,_78,_158)] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_177,_59)] [&.facebook-link:hover]:[background-attachment:initial] [&.facebook-link:hover]:[background-clip:initial] [&.facebook-link:hover]:[background-color:rgb(234,_241,_255)] [&.facebook-link:hover]:[background-image:initial] [&.facebook-link:hover]:[background-origin:initial] [&.facebook-link:hover]:[background-position:initial] [&.facebook-link:hover]:[background-repeat:initial] [&.facebook-link:hover]:[background-size:initial]" :href="headerContacts.socials.facebook" target="_blank" rel="noopener noreferrer" :aria-label="copy('PIISC on Facebook', 'ফেসবুকে পিআইআইএসসি')"><Facebook :size="18" aria-hidden="true" /></a>
      </div>
      <ContactForm />
    </div></section>
  </main>
</template>
