<script setup>
import { BookOpen, HeartHandshake, Compass, Sparkles, ShieldCheck, Users } from 'lucide-vue-next'
import PageHero from '../components/PageHero.vue'
import BaseButton from '../components/BaseButton.vue'
import learning from '../assets/images/group-work.jpg'
const values = [
  { icon: ShieldCheck, title: 'Faith & integrity', text: 'Let Islamic values guide everyday choices, with honesty, sincerity and respect.' },
  { icon: BookOpen, title: 'A love of knowledge', text: 'Ask thoughtful questions, explore new ideas and develop the confidence to keep learning.' },
  { icon: HeartHandshake, title: 'Kindness & service', text: 'Care for others, appreciate our differences and contribute to the community.' },
  { icon: Sparkles, title: 'Excellence through effort', text: 'Take pride in progress, learn from challenges and bring care to every task.' },
]
</script>
<template>
  <PageHero :eyebrow="$tr(&quot;Discover PIISC&quot;)" :title="$tr(&quot;Education with purpose. A future with possibility.&quot;)" :lead="$tr(&quot;Our approach brings learning, Islamic values and personal growth together — helping children build knowledge and character, side by side.&quot;)" />
  <section class="section"><div class="container details-intro [&&]:grid [@media(max-width:640px)]:[&&]:grid-cols-[1fr] [@media(width>640px)]:[&&]:grid-cols-[1fr_1fr] [&&]:items-center [@media(max-width:900px)]:[&&]:gap-x-[35px] [@media(width>900px)]:[&&]:gap-x-[70px] [@media(max-width:900px)]:[&&]:gap-y-[35px] [@media(width>900px)]:[&&]:gap-y-[70px]">
    <div class="details-photo [&&]:relative [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[border-bottom-left-radius:4px] [&&]:[border-bottom-right-radius:4px] [&&]:[border-top-left-radius:4px] [&&]:[border-top-right-radius:4px]"><img class="[@media(max-width:640px)]:[&&]:h-[320px] [@media(width>640px)]:[&&]:h-[460px] [&&]:w-[100%] [&&]:object-cover [&&]:[transition-behavior:normal] [&&]:[transition-delay:0s] [&&]:[transition-duration:0.7s] [&&]:[transition-property:transform] [&&]:[transition-timing-function:ease] [.details-photo:hover_img&]:[transform:scale(1.04)]" :src="learning" :alt="$tr(&quot;PIISC students learning together through group work&quot;)" /><span class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:initial] [&&]:[background-image:linear-gradient(transparent,_rgba(8,_33,_61,_0.9))] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:white] [&&]:p-[26px]">{{ $tr("Growing together, every day.") }}</span></div>
    <div><span class="eyebrow">{{ $tr("Our purpose") }}</span><h2 class="[&&]:[font-size:clamp(30px,_3.1vw,_46px)] [&&]:leading-[1.18] [&&]:[color:rgb(10,_41,_72)] [&&]:m-[15px_0px_22px_0px]">{{ $tr("A strong foundation for learning and life.") }}</h2><p class="[&&]:[color:rgb(83,_97,_106)] [.details-intro_p_+_p&]:mt-[16px]">{{ $tr("At Peace International Islamic School & College, our educational vision connects academic learning with faith, thoughtful choices and care for others.") }}</p><p class="[&&]:[color:rgb(83,_97,_106)] [.details-intro_p_+_p&]:mt-[16px]">{{ $tr("We want each child to grow in curiosity and confidence, with a sense of responsibility that extends beyond the classroom.") }}</p><BaseButton class="[&&&]:mt-[28px]" to="/contact">{{ $tr("Talk to our team") }}</BaseButton></div>
  </div></section>
  <section class="details-purpose [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(243,_246,_242)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:p-[65px_0px]"><div class="container purpose-cards [&&]:grid [@media(max-width:640px)]:[&&]:grid-cols-[1fr] [@media(width>640px)]:[&&]:grid-cols-[1fr_1fr] [&&]:gap-x-[28px] [&&]:gap-y-[28px]">
    <article class="[&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:white] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-top-color:rgb(184,_147,_69)] [&&]:[border-top-style:solid] [&&]:[border-top-width:3px] [&&]:[transition-behavior:normal,_normal,_normal] [&&]:[transition-delay:0s,_0s,_0s] [&&]:[transition-duration:0.35s,_0.35s,_0.35s] [&&]:[transition-property:transform,_box-shadow,_border-color] [&&]:[transition-timing-function:ease,_ease,_ease] [@media(max-width:640px)]:[&&]:p-[28px] [@media(width>640px)]:[&&]:p-[40px] [.purpose-cards_article&:hover]:[box-shadow:rgba(24,_49,_62,_0.07)_0px_18px_40px] [.purpose-cards_article&:hover]:[transform:translateY(-7px)] [.purpose-cards_article&:hover]:[border-color:rgb(184,_147,_69)]"><Compass class="[&&]:mb-[22px] [&&]:[color:rgb(14,_91,_74)]" :size="32" aria-hidden="true"/><span class="eyebrow">{{ $tr("Our mission") }}</span><h2 class="[&&]:[font-size:32px] [&&]:leading-[1.18] [&&]:[color:rgb(10,_41,_72)] [&&]:m-[15px_0px_22px_0px]">{{ $tr("Learning that shapes character.") }}</h2><p class="[&&]:[color:rgb(83,_97,_106)]">{{ $tr("To create a caring learning community where children develop knowledge, practise Islamic values and discover how they can make a positive contribution.") }}</p></article>
    <article class="[&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:white] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-top-color:rgb(184,_147,_69)] [&&]:[border-top-style:solid] [&&]:[border-top-width:3px] [&&]:[transition-behavior:normal,_normal,_normal] [&&]:[transition-delay:0s,_0s,_0s] [&&]:[transition-duration:0.35s,_0.35s,_0.35s] [&&]:[transition-property:transform,_box-shadow,_border-color] [&&]:[transition-timing-function:ease,_ease,_ease] [@media(max-width:640px)]:[&&]:p-[28px] [@media(width>640px)]:[&&]:p-[40px] [.purpose-cards_article&:hover]:[box-shadow:rgba(24,_49,_62,_0.07)_0px_18px_40px] [.purpose-cards_article&:hover]:[transform:translateY(-7px)] [.purpose-cards_article&:hover]:[border-color:rgb(184,_147,_69)]"><Sparkles class="[&&]:mb-[22px] [&&]:[color:rgb(14,_91,_74)]" :size="32" aria-hidden="true"/><span class="eyebrow">{{ $tr("Our vision") }}</span><h2 class="[&&]:[font-size:32px] [&&]:leading-[1.18] [&&]:[color:rgb(10,_41,_72)] [&&]:m-[15px_0px_22px_0px]">{{ $tr("Confident learners. Considerate people.") }}</h2><p class="[&&]:[color:rgb(83,_97,_106)]">{{ $tr("To inspire young people to approach their future with understanding, integrity and the willingness to keep growing.") }}</p></article>
  </div></section>
  <section id="value" class="section values-section"><div class="container"><span class="eyebrow">{{ $tr("What guides us") }}</span><h2 class="[&&]:[font-size:clamp(30px,_3.1vw,_46px)] [&&]:leading-[1.18] [&&]:[color:rgb(10,_41,_72)] [&&]:m-[15px_0px_22px_0px]">{{ $tr("Our values, in everyday life.") }}</h2><p class="values-lead [&&]:[color:rgb(83,_97,_106)] [&&]:max-w-[620px]">{{ $tr("The habits we encourage today help shape the people our children become tomorrow.") }}</p><div class="values-grid [&&]:mt-[38px] [&&]:grid [@media(max-width:640px)]:[&&]:grid-cols-[1fr] [@media(width>640px)_and_(max-width:900px)]:[&&]:grid-cols-[1fr_1fr] [@media(width>900px)]:[&&]:grid-cols-[repeat(4,_1fr)] [&&]:gap-x-[22px] [&&]:gap-y-[22px]"><article class="[&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[transition-behavior:normal,_normal,_normal] [&&]:[transition-delay:0s,_0s,_0s] [&&]:[transition-duration:0.35s,_0.35s,_0.35s] [&&]:[transition-property:transform,_box-shadow,_border-color] [&&]:[transition-timing-function:ease,_ease,_ease] [&&]:p-[30px_25px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_229,_222)] [.values-grid_article&:hover]:[box-shadow:rgba(24,_49,_62,_0.07)_0px_18px_40px] [.values-grid_article&:hover]:[transform:translateY(-7px)] [.values-grid_article&:hover]:[border-color:rgb(184,_147,_69)]" v-for="(value, index) in values" :key="value.title"><div class="value-top [&&]:mb-[32px] [&&]:flex [&&]:items-center [&&]:justify-between [&&]:[color:rgb(14,_91,_74)]"><component :is="value.icon" :size="28" aria-hidden="true"/><span class="[&&]:[color:rgb(167,_125,_49)] [&&]:[font-size:13px]">0{{ $tr(index + 1) }}</span></div><h3 class="[&&]:mb-[14px] [&&]:[font-size:21px]">{{ $tr(value.title) }}</h3><p class="[&&]:[color:rgb(83,_97,_106)]">{{ $tr(value.text) }}</p></article></div></div></section>
  <section class="section family-section [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial]"><div class="container family-layout [&&]:grid [@media(max-width:640px)]:[&&]:grid-cols-[1fr] [@media(width>640px)]:[&&]:grid-cols-[1fr_1fr] [@media(max-width:900px)]:[&&]:gap-x-[35px] [@media(width>900px)]:[&&]:gap-x-[70px] [@media(max-width:900px)]:[&&]:gap-y-[35px] [@media(width>900px)]:[&&]:gap-y-[70px]"><div><Users class="[&&]:mb-[24px] [&&]:[color:rgb(228,_198,_131)]" :size="34" aria-hidden="true"/><span class="eyebrow">{{ $tr("A partnership with families") }}</span><h2 class="[&&]:[font-size:clamp(30px,_3.1vw,_46px)] [&&]:leading-[1.18] [&&]:[color:white] [&&]:m-[15px_0px_22px_0px]">{{ $tr("Every child's journey matters.") }}</h2></div><div><p class="[&&]:[color:rgb(220,_230,_231)]">{{ $tr("Choosing a school is an important family decision. We welcome your questions about learning, school life and the values that guide PIISC.") }}</p><ul class="[&&]:mt-[22px] [&&]:pl-[20px] [&&]:leading-[2]"><li class="[&&]:[color:rgb(220,_230,_231)]">{{ $tr("Open conversations between school and home.") }}</li><li class="[&&]:[color:rgb(220,_230,_231)]">{{ $tr("Encouragement for curiosity, effort and personal growth.") }}</li><li class="[&&]:[color:rgb(220,_230,_231)]">{{ $tr("Respect, kindness and responsibility in our community.") }}</li></ul><BaseButton class="[&&&]:mt-[28px]" to="/contact">{{ $tr("Make an inquiry") }}</BaseButton></div></div></section>
</template>
