<script setup>
import { Presentation, BookOpen, FlaskConical, Monitor, Heart, Trophy, ShieldCheck, Palette, Users } from 'lucide-vue-next'
import cover from '../assets/images/studytime.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const text = pair => pair[language.value === 'bn' ? 1 : 0]
const facilities = [
 {icon:Presentation,title:['Classrooms & learning spaces','শ্রেণিকক্ষ ও শিক্ষার পরিবেশ'],detail:['Spaces for lessons, discussion, and learning together.','পাঠদান, আলোচনা ও একসঙ্গে শেখার পরিবেশ।']},
 {icon:BookOpen,title:['Library & reading resources','লাইব্রেরি ও পাঠ উপকরণ'],detail:['Ask the school about its current collection and reading resources.','বর্তমান বইয়ের সংগ্রহ ও পাঠ উপকরণ সম্পর্কে স্কুলে জানুন।']},
 {icon:FlaskConical,title:['Science learning','বিজ্ঞান শিক্ষা'],detail:['Contact us for details of practical learning and laboratory arrangements.','ব্যবহারিক শিক্ষা ও ল্যাবের ব্যবস্থা সম্পর্কে জানতে যোগাযোগ করুন।']},
 {icon:Monitor,title:['Computer & digital learning','কম্পিউটার ও ডিজিটাল শিক্ষা'],detail:['Confirm available equipment and access for your child’s grade.','আপনার সন্তানের শ্রেণির জন্য সরঞ্জাম ও ব্যবহারের সুযোগ নিশ্চিত করুন।']},
 {icon:Heart,title:['Faith & Islamic learning','বিশ্বাস ও ইসলামী শিক্ষা'],detail:['Learn about arrangements for prayer and Islamic learning at PIISC.','পিআইআইএসসিতে নামাজ ও ইসলামী শিক্ষার ব্যবস্থা সম্পর্কে জানুন।']},
 {icon:Trophy,title:['Sports & active play','খেলাধুলা ও শরীরচর্চা'],detail:['Explore school activities and ask about current play-space access.','স্কুলের কার্যক্রম দেখুন এবং খেলার স্থান ব্যবহারের সুযোগ সম্পর্কে জানুন।']},
 {icon:Palette,title:['Creative classroom activities','সৃজনশীল শ্রেণিকক্ষ কার্যক্রম'],detail:['Making, drawing, and shared projects encourage expression and discovery.','তৈরি করা, আঁকা ও যৌথ প্রকল্প আত্মপ্রকাশ ও অনুসন্ধানকে উৎসাহিত করে।']},
 {icon:Users,title:['Family & school partnership','পরিবার ও স্কুলের অংশীদারিত্ব'],detail:['Connect with the school team about learning needs and student progress.','শিক্ষার প্রয়োজন ও শিক্ষার্থীর অগ্রগতি নিয়ে স্কুলের সঙ্গে কথা বলুন।']},
 {icon:ShieldCheck,title:['Campus safety arrangements','ক্যাম্পাসের নিরাপত্তা ব্যবস্থা'],detail:['Discuss supervision, access, and current safety procedures during your visit.','পরিদর্শনের সময় তত্ত্বাবধান, প্রবেশাধিকার ও নিরাপত্তার নিয়ম সম্পর্কে জানুন।']},
]
</script>
<template>
 <div class="facilities-page [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:initial] [&&]:[background-image:linear-gradient(rgb(255,_255,_255),_rgb(249,_250,_255))] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(10,_41,_72)]">
  <section class="facilities-hero [&&]:relative [&&]:isolate [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&.facilities-hero::after]:absolute [&.facilities-hero::after]:bottom-[0px] [&.facilities-hero::after]:left-[0px] [&.facilities-hero::after]:right-[0px] [&.facilities-hero::after]:top-[0px] [&.facilities-hero::after]:z-[-1] [&.facilities-hero::after]:[background-attachment:initial] [&.facilities-hero::after]:[background-clip:initial] [&.facilities-hero::after]:[background-color:initial] [&.facilities-hero::after]:[background-image:linear-gradient(100deg,_rgba(41,_78,_158,_0.96),_rgba(41,_78,_158,_0.86)_65%,_rgba(10,_41,_72,_0.72))] [&.facilities-hero::after]:[background-origin:initial] [&.facilities-hero::after]:[background-position:initial] [&.facilities-hero::after]:[background-repeat:initial] [&.facilities-hero::after]:[background-size:initial] [&.facilities-hero::after]:[content:'']" aria-labelledby="facilities-title">
   <img class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:z-[-2] [&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [&&]:[object-position:center_45%]" :src="cover" :alt="text(['Students learning at PIISC','পিআইআইএসসিতে শিক্ষার্থীদের পাঠদান'])" fetchpriority="high"/>
   <div class="facilities-width facilities-hero-copy [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:640px)]:[&&]:[padding-block-end:64px] [@media(width>640px)]:[&&]:[padding-block-end:clamp(64px,_7vw,_112px)] [@media(max-width:640px)]:[&&]:[padding-block-start:56px] [@media(width>640px)]:[&&]:[padding-block-start:clamp(64px,_7vw,_112px)]">
    <p class="facilities-eyebrow [&&]:[color:rgb(243,_204,_72)] [&&]:[font-size:13px] [&&]:mb-[24px] [&&]:font-[700] [&&]:tracking-[0.18em] [.facilities-hero-copy>p&:last-child]:[color:rgb(237,_242,_250)] [.facilities-hero-copy>p&:last-child]:[font-size:clamp(17px,_1.4vw,_22px)] [.facilities-hero-copy>p&:last-child]:max-w-[930px] [.facilities-hero-copy>p&:last-child]:leading-[1.8]">{{ text(['FACILITIES','সুযোগ-সুবিধা']) }}</p>
    <h1 class="[&&]:[color:rgb(255,_255,_255)] [&&]:[font-size:clamp(36px,_5vw,_74px)] [&&]:mb-[26px] [&&]:leading-[1.12]" id="facilities-title">{{ text(['Facilities at a Glance','এক নজরে সুযোগ-সুবিধা']) }}</h1>
    <p class="[.facilities-hero-copy>p&:last-child]:max-w-[930px] [.facilities-hero-copy>p&:last-child]:[font-size:clamp(17px,_1.4vw,_22px)] [.facilities-hero-copy>p&:last-child]:leading-[1.8] [.facilities-hero-copy>p&:last-child]:[color:rgb(237,_242,_250)]">{{ text(['Explore the spaces and support behind learning at Peace International Islamic School & College, from classroom discovery to creativity, faith, and active school life.','পিস ইন্টারন্যাশনাল ইসলামিক স্কুল অ্যান্ড কলেজের শ্রেণিকক্ষের শিক্ষা, সৃজনশীলতা, বিশ্বাস ও সক্রিয় স্কুলজীবনের পরিবেশ এবং সহায়তা সম্পর্কে জানুন।']) }}</p>
   </div>
  </section>
  <section class="facilities-width facilities-content [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:640px)]:[&&]:[padding-block-end:30px] [@media(width>640px)]:[&&]:[padding-block-end:44px] [@media(max-width:640px)]:[&&]:[padding-block-start:40px] [@media(width>640px)]:[&&]:[padding-block-start:64px]" :aria-label="text(['PIISC facilities and learning support','পিআইআইএসসির সুযোগ-সুবিধা ও শিক্ষায় সহায়তা'])">
   <ul class="facilities-cards [&&]:grid [@media(max-width:640px)]:[&&]:grid-cols-[1fr] [@media(width>640px)_and_(max-width:1050px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [@media(width>1050px)]:[&&]:grid-cols-[repeat(3,_minmax(0px,_1fr))] [@media(max-width:640px)]:[&&]:gap-x-[14px] [@media(width>640px)]:[&&]:gap-x-[20px] [@media(max-width:640px)]:[&&]:gap-y-[14px] [@media(width>640px)]:[&&]:gap-y-[20px] [&&]:[list-style-image:initial] [&&]:[list-style-position:initial] [&&]:[list-style-type:none] [&&]:m-[0px] [&&]:p-[0px]">
    <li class="[&&]:flex [&&]:items-start [&&]:gap-x-[18px] [&&]:gap-y-[18px] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:white] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[box-shadow:rgba(23,_58,_106,_0.027)_0px_12px_32px] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.3s,_0.3s,_0.3s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:transform,_border-color,_box-shadow] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [@media(max-width:640px)]:[&&]:p-[22px] [@media(width>640px)]:[&&]:p-[26px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(221,_229,_241)] [.facilities-cards_li&:hover]:[box-shadow:rgba(23,_58,_106,_0.075)_0px_18px_38px] [@media(prefers-reduced-motion:no-preference)]:[.facilities-cards_li&:hover]:[transform:translateY(-4px)] [@media(prefers-reduced-motion:reduce)]:[.facilities-cards_li&:hover]:[transform:none] [.facilities-cards_li&:hover]:[border-color:rgb(217,_179,_61)]" v-for="facility in facilities" :key="facility.title[0]">
     <span class="facility-symbol [&&]:grid [&&]:h-[48px] [&&]:items-center [&&]:[justify-items:center] [&&]:[border-bottom-left-radius:50%] [&&]:[border-bottom-right-radius:50%] [&&]:[border-top-left-radius:50%] [&&]:[border-top-right-radius:50%] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_248,_216)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(41,_78,_158)] [&&]:[flex-basis:48px] [&&]:[flex-grow:0] [&&]:[flex-shrink:0] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.3s,_0.3s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:background,_color] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [.facilities-cards_li:hover_&.facility-symbol]:[background-color:rgb(41,_78,_158)] [.facilities-cards_li:hover_&.facility-symbol]:[color:rgb(243,_204,_72)]"><component :is="facility.icon" :size="23" :stroke-width="1.7" aria-hidden="true"/></span>
     <div><h2 class="[&&]:[font-size:17px] [&&]:leading-[1.5] [&&]:[color:rgb(10,_41,_72)] [&&]:m-[0px_0px_9px_0px]">{{ text(facility.title) }}</h2><p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:14px] [&&]:leading-[1.75]">{{ text(facility.detail) }}</p></div>
    </li>
   </ul>
   <p class="facility-note [&&]:[color:rgb(103,_118,_139)] [&&]:[font-size:14px] [&&]:mt-[28px] [&&]:max-w-[1100px] [&&]:leading-[1.8]">{{ text(['Facilities and access may vary by grade. Library, laboratory, prayer-space, and safety arrangements are awaiting confirmation; please contact PIISC for current details or arrange a visit.','শ্রেণিভেদে সুবিধা ও ব্যবহারের সুযোগ আলাদা হতে পারে। লাইব্রেরি, ল্যাব, নামাজের স্থান ও নিরাপত্তার ব্যবস্থা নিশ্চিতকরণের অপেক্ষায় রয়েছে; বর্তমান তথ্য বা পরিদর্শনের জন্য পিআইআইএসসিতে যোগাযোগ করুন।']) }}</p>
  </section>
 </div>
</template>
