<script setup>
import { computed, nextTick, onBeforeUnmount, ref } from 'vue'
import { Images, Grid2X2, CalendarDays, Trophy, GraduationCap, Building2, ChevronRight, ChevronLeft, X } from 'lucide-vue-next'
import { galleryPhotos } from '../data/gallery.js'
import galleryCover from '../assets/images/group-work.jpg'
const categories = [{name:'All Photos',icon:Grid2X2},{name:'Events',icon:CalendarDays},{name:'Sports',icon:Trophy},{name:'Academics',icon:GraduationCap},{name:'Campus',icon:Building2}]
const category = ref('All Photos')
const filtered = computed(()=>galleryPhotos.filter(photo=>category.value==='All Photos'||photo.category===category.value))
const selected = ref(null)
const selectedIndex = computed(()=>filtered.value.findIndex(photo=>photo.id===selected.value?.id))
const dialog = ref(null)
const closing = ref(false)
let previousFocus, previousOverflow, closeTimer
let locked = false
async function openPhoto(photo,event){previousFocus=event.currentTarget;selected.value=photo;await nextTick();previousOverflow=document.body.style.overflow;dialog.value.showModal();document.body.style.overflow='hidden';locked=true}
function restore(){if(!locked)return;document.body.style.overflow=previousOverflow;locked=false;previousFocus?.focus({preventScroll:true})}
function close(){if(closing.value)return;closing.value=true;const delay=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:200;closeTimer=setTimeout(()=>{dialog.value?.close();closing.value=false;selected.value=null;restore()},delay)}
function move(direction){if(closing.value)return;selected.value=filtered.value[(selectedIndex.value+direction+filtered.value.length)%filtered.value.length]}
onBeforeUnmount(()=>{clearTimeout(closeTimer);dialog.value?.close();restore()})
</script>
<template>
 <section class="gallery-banner">
  <img class="gallery-cover-image" :src="galleryCover" :alt="$tr('Students working together at PIISC')" fetchpriority="high"/>
  <div class="gallery-width gallery-banner-inner"><span class="media-label"><Images :size="16" aria-hidden="true"/>{{ $tr('Gallery') }}</span><h1>{{ $tr('School ') }}{{ $tr('Gallery') }}</h1><nav :aria-label="$tr('Breadcrumb')"><RouterLink to="/">{{ $tr('Home') }}</RouterLink><ChevronRight :size="16" aria-hidden="true"/><span aria-current="page">{{ $tr('Gallery') }}</span></nav></div>
 </section>
 <section class="gallery-section"><div class="gallery-width">
  <div class="gallery-filters" role="group" :aria-label="$tr('Filter photos by category')"><button v-for="item in categories" :key="item.name" type="button" :aria-pressed="category===item.name" :class="{active:category===item.name}" @click="category=item.name"><component :is="item.icon" :size="17" aria-hidden="true"/>{{ $tr(item.name) }}</button></div>
  <p class="sr-only" role="status">{{ $tr(filtered.length) }}{{ $tr(' photos in ') }}{{ $tr(category) }}</p>
  <TransitionGroup name="gallery-card" tag="div" class="school-gallery-grid"><figure v-for="photo in filtered" :key="photo.id" class="gallery-photo-card"><button type="button" class="gallery-photo-button" :aria-label="$tr(`Open photo: ${photo.caption}`)" @click="openPhoto(photo,$event)"><img :src="photo.image" :alt="$tr(photo.caption)" loading="lazy" width="600" height="480"/><span class="photo-overlay" aria-hidden="true"></span><span class="photo-hover-caption" aria-hidden="true">{{ $tr(photo.caption) }}</span></button><figcaption class="sr-only">{{ $tr(photo.caption) }}</figcaption></figure></TransitionGroup>
 </div></section>
 <Teleport to="body"><dialog ref="dialog" class="gallery-lightbox" :class="{'is-closing':closing}" :aria-label="$tr('School photo viewer')" aria-describedby="gallery-photo-caption" @cancel.prevent="close" @close="restore" @click="event=>{if(event.target===dialog)close()}" @keydown.left.prevent="move(-1)" @keydown.right.prevent="move(1)"><div v-if="selected" class="lightbox-panel"><div class="lightbox-toolbar"><span>{{ $tr(selected.category) }} <span class="lightbox-count">{{ $tr(selectedIndex+1) }} / {{ $tr(filtered.length) }}</span></span><button type="button" autofocus :aria-label="$tr('Close photo viewer')" @click="close"><X :size="24" aria-hidden="true"/></button></div><div class="lightbox-image-area"><Transition name="lightbox-photo" mode="out-in"><img :key="selected.id" :src="selected.image" :alt="$tr(selected.caption)"/></Transition><button type="button" class="lightbox-previous" :aria-label="$tr('Previous photo')" @click="move(-1)"><ChevronLeft aria-hidden="true"/></button><button type="button" class="lightbox-next" :aria-label="$tr('Next photo')" @click="move(1)"><ChevronRight aria-hidden="true"/></button></div><p id="gallery-photo-caption" class="lightbox-caption" aria-live="polite">{{ $tr(selected.caption) }}</p></div></dialog></Teleport>
</template>
<style scoped>
.gallery-width{width:calc(100% - clamp(32px,6.5vw,128px));max-width:1800px;margin-inline:auto}.gallery-banner{position:relative;isolation:isolate;overflow:hidden;background:#0a2948;color:white}.gallery-cover-image{position:absolute;inset:0;z-index:-2;width:100%;height:100%;object-fit:cover;object-position:center 45%}.gallery-banner::after{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(100deg,#294e9ef5,#294e9edb 65%,#0a2948bc)}.gallery-banner-inner{padding-block:clamp(64px,7vw,112px)}.media-label{display:inline-flex;align-items:center;gap:10px;color:#f3cc48;font-size:13px;font-weight:700;letter-spacing:.18em;text-transform:uppercase}.gallery-banner h1{font-size:clamp(36px,5vw,74px);margin:24px 0 26px;color:white;line-height:1.12}.gallery-banner nav{display:flex;align-items:center;gap:8px;font-size:16px;color:#edf2fa}.gallery-banner nav span{color:#f3cc48;font-weight:700}.gallery-banner nav a:hover{text-decoration:underline;text-underline-offset:4px}
.gallery-section{padding:64px 0 80px;background:#f8f9fc;min-height:550px}.gallery-filters{display:flex;justify-content:center;flex-wrap:wrap;gap:12px;margin-bottom:38px}.gallery-filters button{display:inline-flex;align-items:center;justify-content:center;gap:9px;border:1px solid #dce4f1;border-radius:6px;padding:13px 23px;background:white;color:#294e9e;font-size:15px;font-weight:700;cursor:pointer;box-shadow:0 3px 10px #173a6a06;transition:color .28s,background .28s,border-color .28s,transform .28s,box-shadow .28s}.gallery-filters button:hover{transform:translateY(-3px);border-color:#d9b33d;background:#fcf5e6;box-shadow:0 8px 20px #173a6a12}.gallery-filters button.active{background:#294e9e;color:white;border-color:#294e9e;box-shadow:0 8px 22px #294e9e25}.gallery-filters button.active svg{color:#f3cc48}.gallery-filters button:focus-visible{outline:3px solid #d9b33d;outline-offset:4px}
.school-gallery-grid{position:relative;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:24px}.gallery-photo-card{margin:0;min-width:0;background:white;border:1px solid #dde5f1;border-radius:6px;overflow:hidden;box-shadow:0 6px 18px #173a6a08;transition:box-shadow .35s}.gallery-photo-card:hover{box-shadow:0 16px 32px #173a6a20}.gallery-photo-button{position:relative;display:block;border:0;padding:0;width:100%;aspect-ratio:1.12;overflow:hidden;background:#edf2fa;cursor:zoom-in}.gallery-photo-button img{width:100%;height:100%;object-fit:cover;transform:scale(1.07) translateX(1.5%);transition:transform .7s ease-out}.gallery-photo-button:hover img,.gallery-photo-button:focus-visible img{transform:scale(1.07) translateX(-1.5%)}.photo-overlay{position:absolute;inset:0;background:linear-gradient(270deg,#0a2948df,#294e9e99);transform:translateX(101%);transition:transform .55s ease-out;pointer-events:none}.gallery-photo-button:hover .photo-overlay,.gallery-photo-button:focus-visible .photo-overlay{transform:translateX(0)}.photo-hover-caption{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;color:white;text-align:center;font-family:Arial,Helvetica,sans-serif;font-size:clamp(18px,1.4vw,24px);font-weight:700;line-height:1.5;opacity:0;transform:translateX(18px);transition:opacity .35s ease-out,transform .55s ease-out;pointer-events:none}.gallery-photo-button:hover .photo-hover-caption,.gallery-photo-button:focus-visible .photo-hover-caption{opacity:1;transform:translateX(0);transition-delay:.12s}.gallery-photo-button:focus-visible{outline-offset:-4px}.gallery-card-enter-active,.gallery-card-leave-active,.gallery-card-move{transition:opacity .3s,transform .3s}.gallery-card-enter-from,.gallery-card-leave-to{opacity:0;transform:translateY(14px) scale(.97)}.gallery-card-leave-active{position:absolute;pointer-events:none}
.gallery-lightbox{max-width:none;max-height:none;width:100%;height:100dvh;margin:0;padding:24px;border:0;background:transparent;color:white;overflow:hidden}.gallery-lightbox[open]{display:grid;place-items:center}.gallery-lightbox::backdrop{background:#061b35eb;backdrop-filter:blur(7px)}.lightbox-panel{width:min(100%,1050px);max-height:100%;min-height:0;display:flex;flex-direction:column;background:#0a2948;border:1px solid #ffffff25;border-radius:6px;overflow:hidden;box-shadow:0 24px 80px #0006;animation:lightbox-open .25s ease both}.lightbox-toolbar{display:flex;justify-content:space-between;align-items:center;padding:10px 16px;color:#f3cc48;font-size:14px;font-weight:700;flex-shrink:0}.lightbox-count{margin-left:15px;color:#dce4f1;font-weight:400}.lightbox-toolbar button,.lightbox-image-area button{display:grid;place-items:center;background:#0a2948cf;color:white;border:1px solid #ffffff40;border-radius:6px;width:42px;height:42px;cursor:pointer;transition:background .2s,transform .2s}.lightbox-toolbar button:hover,.lightbox-image-area button:hover{background:#294e9e;transform:scale(1.06)}.lightbox-image-area{position:relative;display:grid;place-items:center;min-height:0;height:min(68dvh,700px);background:#061b35}.lightbox-image-area>img{width:100%;height:100%;min-height:0;object-fit:contain}.lightbox-image-area button{position:absolute;top:50%;margin-top:-21px}.lightbox-previous{left:14px}.lightbox-next{right:14px}.lightbox-caption{padding:18px 24px;font-size:16px;line-height:1.5;color:#edf2fa;flex-shrink:0}.is-closing .lightbox-panel{animation:lightbox-close .2s ease both}.lightbox-photo-enter-active,.lightbox-photo-leave-active{transition:opacity .16s}.lightbox-photo-enter-from,.lightbox-photo-leave-to{opacity:0}@keyframes lightbox-open{from{opacity:0;transform:translateY(18px) scale(.96)}to{opacity:1;transform:none}}@keyframes lightbox-close{to{opacity:0;transform:translateY(10px) scale(.97)}}
@media(max-width:1000px){.school-gallery-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}}@media(max-width:760px){.school-gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.gallery-section{padding:42px 0 60px}.gallery-filters{gap:8px;margin-bottom:28px}.gallery-filters button{padding:11px 16px;font-size:13px}.gallery-banner-inner{padding-block:56px 64px}.gallery-lightbox{padding:12px}.lightbox-caption{padding:14px 16px;font-size:14px}}@media(max-width:440px){.school-gallery-grid{grid-template-columns:1fr}.gallery-photo-button{aspect-ratio:1.3}}@media(prefers-reduced-motion:reduce){.lightbox-panel,.is-closing .lightbox-panel{animation:none}.gallery-card-enter-active,.gallery-card-leave-active,.gallery-card-move,.lightbox-photo-enter-active,.lightbox-photo-leave-active,.gallery-photo-button img,.photo-overlay,.photo-hover-caption,.gallery-filters button,.gallery-photo-card,.lightbox-toolbar button,.lightbox-image-area button{transition:none}}
</style>
