<script setup>
import { leaders } from '../data/leadership.js'
import classroom from '../assets/images/studytime.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const messageLeaders = ['principal', 'chairman'].map(id => leaders.find(leader => leader.id === id)).filter(Boolean)
const copy = (en, bn) => language.value === 'bn' ? bn : en
</script>

<template>
  <div class="hos-page [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:initial] [&&]:[background-image:linear-gradient(rgb(255,_255,_255),_rgb(248,_249,_252))] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(10,_41,_72)]">
    <section class="hos-hero [&&]:relative [&&]:isolate [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&.hos-hero::after]:absolute [&.hos-hero::after]:bottom-[0px] [&.hos-hero::after]:left-[0px] [&.hos-hero::after]:right-[0px] [&.hos-hero::after]:top-[0px] [&.hos-hero::after]:z-[-1] [&.hos-hero::after]:[background-attachment:initial] [&.hos-hero::after]:[background-clip:initial] [&.hos-hero::after]:[background-color:initial] [&.hos-hero::after]:[background-image:linear-gradient(100deg,_rgba(41,_78,_158,_0.96),_rgba(41,_78,_158,_0.85)_65%,_rgba(10,_41,_72,_0.79))] [&.hos-hero::after]:[background-origin:initial] [&.hos-hero::after]:[background-position:initial] [&.hos-hero::after]:[background-repeat:initial] [&.hos-hero::after]:[background-size:initial] [&.hos-hero::after]:[content:'']" aria-labelledby="hos-title">
      <img class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:z-[-2] [&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [&&]:[object-position:center_45%]" :src="classroom" :alt="$tr('Students learning at PIISC')" fetchpriority="high" />
      <div class="hos-width hos-hero-content [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:760px)]:[&&]:[padding-block-end:64px] [@media(width>760px)]:[&&]:[padding-block-end:clamp(64px,_7vw,_112px)] [@media(max-width:760px)]:[&&]:[padding-block-start:56px] [@media(width>760px)]:[&&]:[padding-block-start:clamp(64px,_7vw,_112px)]">
        <p class="hos-eyebrow [&&]:[font-size:13px] [&&]:mb-[24px] [&&]:font-[700] [&&]:tracking-[0.18em] [&&]:[color:rgb(243,_204,_72)] [.hos-hero-content>p&:last-child]:[font-size:clamp(17px,_1.5vw,_23px)] [.hos-hero-content>p&:last-child]:[color:rgb(237,_242,_250)] [.hos-hero-content>p&:last-child]:max-w-[1000px] [.hos-hero-content>p&:last-child]:leading-[1.75]">{{ copy('LEADERSHIP MESSAGE', 'প্রতিষ্ঠান প্রধানের বার্তা') }}</p>
        <h1 class="[&&]:max-w-[1100px] [&&]:[color:rgb(255,_255,_255)] [&&]:[font-size:clamp(36px,_5vw,_78px)] [&&]:leading-[1.1] [&&]:[text-wrap-mode:initial] [&&]:[text-wrap-style:balance] [&&]:m-[0px_0px_28px_0px]" id="hos-title">{{ copy('Message from the Head of School', 'প্রতিষ্ঠান প্রধানের বার্তা') }}</h1>
        <p class="[.hos-hero-content>p&:last-child]:[font-size:clamp(17px,_1.5vw,_23px)] [.hos-hero-content>p&:last-child]:max-w-[1000px] [.hos-hero-content>p&:last-child]:leading-[1.75] [.hos-hero-content>p&:last-child]:[color:rgb(237,_242,_250)]">{{ copy('Encouraging curiosity, strengthening character, and growing together in faith.', 'কৌতূহলকে উৎসাহিত করে, চরিত্র গঠনে ও বিশ্বাসে একসঙ্গে এগিয়ে চলা।') }}</p>
      </div>
    </section>

    <section v-for="principal in messageLeaders" :key="principal.id" class="hos-width hos-message-section [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [&&]:[padding-block-end:48px] [&&]:[padding-block-start:clamp(40px,_4vw,_70px)] [@media(max-width:760px)]:[&&]:pb-[30px] [.hos-message-section_+_&.hos-message-section]:pt-[0px]" :aria-labelledby="`message-${principal.id}`">
      <div class="hos-message-card [&&]:grid [@media(max-width:760px)]:[&&]:grid-cols-[1fr] [@media(width>760px)]:[&&]:grid-cols-[minmax(220px,_0.8fr)_minmax(0px,_2fr)] [&&]:[align-items:start] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [@media(max-width:760px)]:[&&]:gap-x-[30px] [@media(width>760px)]:[&&]:gap-x-[clamp(30px,_5vw,_80px)] [@media(max-width:760px)]:[&&]:gap-y-[30px] [@media(width>760px)]:[&&]:gap-y-[clamp(30px,_5vw,_80px)] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[box-shadow:rgba(23,_58,_106,_0.03)_0px_18px_50px] [&&]:p-[clamp(24px,_3vw,_48px)] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(221,_229,_241)]">
        <aside class="hos-profile [@media(max-width:760px)]:[&&]:max-w-[360px]">
          <img class="[@media(max-width:760px)]:[&&]:max-h-[340px] [@media(width>760px)]:[&&]:max-h-[440px] [&&]:w-[100%] [&&]:object-cover [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[object-position:center_top] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(243,_245,_249)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [@media(max-width:760px)]:[&&]:h-[auto] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(224,_230,_239)]" :src="principal.photo" :alt="$tr(principal.name)" width="360" height="400" />
          <h2 class="[&&]:[color:rgb(41,_78,_158)] [&&]:[font-size:21px] [&&]:leading-[1.4] [&&]:m-[22px_0px_8px_0px]">{{ $tr(principal.name) }}</h2>
          <p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:16px] [&&]:leading-[1.7]">{{ principal.id === 'chairman' ? copy('Chairman', 'চেয়ারম্যান') : copy('Principal · Head of School', 'অধ্যক্ষ · প্রতিষ্ঠান প্রধান') }}</p>
          <p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:16px] [&&]:leading-[1.7]">{{ copy('Peace International Islamic School & College', 'পিস ইন্টারন্যাশনাল ইসলামিক স্কুল অ্যান্ড কলেজ') }}</p>
        </aside>
        <article class="hos-letter">
          <h2 :id="`message-${principal.id}`" class="hos-message-heading [&&]:[color:rgb(41,_78,_158)] [&&]:[font-size:clamp(23px,_2vw,_30px)] [&&]:leading-[1.3] [&&]:m-[0px_0px_24px_0px]">{{ principal.id === 'chairman' ? copy('Message from the Chairman', 'চেয়ারম্যানের বার্তা') : copy('Message from the Principal', 'অধ্যক্ষের বার্তা') }}</h2>
          <p class="hos-greeting [&&&]:[color:rgb(41,_78,_158)] [&&&]:[font-size:26px] [&&&]:leading-[1.7] [&&&]:w-[fit-content] [&&&]:[font-family:'Traditional_Arabic',_'Noto_Naskh_Arabic',_'Times_New_Roman',_serif] [&&&]:m-[0px_0px_26px_0px] [.hos-letter>p&:last-child]:m-[0px]" lang="ar" dir="rtl">السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ</p>
          <p v-if="principal.draft" class="hos-draft [&&&]:[color:rgb(140,_105,_30)] [&&&]:[font-size:12px] [&&&]:leading-[1.85] [&&&]:pl-[12px] [&&&]:[border-left-color:rgb(217,_179,_61)] [&&&]:[border-left-style:solid] [&&&]:[border-left-width:2px] [&&&]:m-[0px_0px_24px_0px] [.hos-letter>p&:last-child]:m-[0px]">{{ copy('Welcome message · Draft pending approval', 'স্বাগত বার্তা · অনুমোদনের অপেক্ষায় খসড়া') }}</p>
          <p class="[&&]:[color:rgb(93,_110,_134)] [&&]:[font-size:clamp(17px,_1.35vw,_21px)] [&&]:leading-[1.85] [&&]:m-[0px_0px_26px_0px] [.hos-letter>p&:last-child]:m-[0px]" v-for="paragraph in principal.paragraphs.slice(1)" :key="paragraph">{{ $tr(paragraph) }}</p>
        </article>
      </div>
    </section>
  </div>
</template>
