<script setup>
import cover from '../assets/images/group-work.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const text = pair => pair[language.value === 'bn' ? 1 : 0]
const areas = [
 {tag:['CONFIDENCE THROUGH COMMUNICATION','যোগাযোগে আত্মবিশ্বাস'],title:['Communication, Language & Literacy','যোগাযোগ, ভাষা ও সাক্ষরতা'],body:['From early reading to thoughtful discussion and extended writing, PIISC encourages students to express ideas clearly. Listening carefully, asking questions, and speaking with honesty and respect support learning across Grades 1–12.','প্রাথমিক পাঠ থেকে আলোচনা ও বিস্তারিত লেখা পর্যন্ত পিআইআইএসসি শিক্ষার্থীদের স্পষ্টভাবে ভাব প্রকাশ করতে উৎসাহিত করে। মনোযোগ দিয়ে শোনা, প্রশ্ন করা এবং সততা ও শ্রদ্ধার সঙ্গে কথা বলা প্রথম–দ্বাদশ শ্রেণির শিক্ষাকে সমৃদ্ধ করে।']},
 {tag:['REASONING WITH CLARITY','স্পষ্ট যুক্তির চর্চা'],title:['Mathematics','গণিত'],body:['Number, pattern, measurement, and problem-solving build a foundation for increasingly complex ideas. Learners are encouraged to explain their reasoning, test different approaches, and connect mathematical understanding with everyday decisions.','সংখ্যা, বিন্যাস, পরিমাপ ও সমস্যা সমাধান ক্রমশ জটিল ধারণা বোঝার ভিত্তি গড়ে তোলে। শিক্ষার্থীদের যুক্তি ব্যাখ্যা, ভিন্ন পদ্ধতি পরীক্ষা এবং গণিতকে দৈনন্দিন সিদ্ধান্তের সঙ্গে যুক্ত করতে উৎসাহিত করা হয়।']},
 {tag:['IDEAS INTO EXPRESSION','ভাবনার প্রকাশ'],title:['Creative Expression','সৃজনশীল প্রকাশ'],body:['Drawing, making, storytelling, and collaborative projects create opportunities to explore original ideas. We value the patience, imagination, and confidence that develop when students create, reflect, and share their work.','আঁকা, তৈরি করা, গল্প বলা ও যৌথ প্রকল্প নতুন ধারণা অন্বেষণের সুযোগ দেয়। কাজ তৈরি, পর্যালোচনা ও উপস্থাপনের মাধ্যমে গড়ে ওঠা ধৈর্য, কল্পনাশক্তি ও আত্মবিশ্বাসকে আমরা গুরুত্ব দিই।']},
 {tag:['CHARACTER IN EVERYDAY LIFE','দৈনন্দিন জীবনে চরিত্র'],title:['Personal, Social & Emotional Development','ব্যক্তিগত, সামাজিক ও মানসিক বিকাশ'],body:['Learning to understand emotions, work with others, and take responsibility is part of growing up. Islamic values of patience, gratitude, kindness, and integrity guide our aspirations for confident and considerate young people.','আবেগ বোঝা, অন্যের সঙ্গে কাজ করা ও দায়িত্ব নেওয়া বেড়ে ওঠার অংশ। ধৈর্য, কৃতজ্ঞতা, সহমর্মিতা ও সততার ইসলামী মূল্যবোধ আত্মবিশ্বাসী ও বিবেচক তরুণ গড়ার লক্ষ্যকে পথ দেখায়।']},
 {tag:['MOVEMENT & WELLBEING','শরীরচর্চা ও সুস্থতা'],title:['Physical Development','শারীরিক বিকাশ'],body:['Active play and participation in school activities help develop coordination, perseverance, and teamwork. As students grow, healthy routines and responsible choices support their wellbeing alongside academic progress.','খেলাধুলা ও স্কুলের কার্যক্রমে অংশগ্রহণ সমন্বয়, অধ্যবসায় ও দলগত দক্ষতা গড়ে তোলে। স্বাস্থ্যকর অভ্যাস ও দায়িত্বশীল সিদ্ধান্ত শিক্ষাগত অগ্রগতির পাশাপাশি সুস্থতায় সহায়তা করে।']},
 {tag:['CURIOSITY ABOUT CREATION','সৃষ্টি সম্পর্কে কৌতূহল'],title:['Understanding the World','বিশ্বকে জানা'],body:['Questions about science, nature, people, and communities encourage students to observe carefully and consider evidence. A sense of wonder and gratitude for Allah’s creation goes alongside respect for others and responsible engagement with the world.','বিজ্ঞান, প্রকৃতি, মানুষ ও সমাজ সম্পর্কে প্রশ্ন শিক্ষার্থীদের মনোযোগ দিয়ে পর্যবেক্ষণ ও প্রমাণ বিবেচনা করতে উৎসাহিত করে। আল্লাহর সৃষ্টির প্রতি বিস্ময় ও কৃতজ্ঞতার সঙ্গে অন্যের প্রতি শ্রদ্ধা ও দায়িত্বশীলতা গড়ে ওঠে।']},
]
const features = [
 [['Purposeful academic learning','উদ্দেশ্যপূর্ণ শিক্ষা'],['Strong foundations that develop across the school and college years.','স্কুল ও কলেজজুড়ে বিকশিত হয় শিক্ষার মজবুত ভিত্তি।']],
 [['Islamic character education','ইসলামী মূল্যবোধে চরিত্র গঠন'],['Faith, reflection, and responsible conduct in daily life.','দৈনন্দিন জীবনে বিশ্বাস, চিন্তা ও দায়িত্বশীল আচরণ।']],
 [['Whole-person development','পরিপূর্ণ বিকাশ'],['Attention to knowledge, character, creativity, and wellbeing.','জ্ঞান, চরিত্র, সৃজনশীলতা ও সুস্থতার প্রতি মনোযোগ।']],
 [['Active participation','সক্রিয় অংশগ্রহণ'],['Questions, practical exploration, and shared learning.','প্রশ্ন, ব্যবহারিক অন্বেষণ ও একসঙ্গে শিক্ষা।']],
 [['Skills for the future','ভবিষ্যতের দক্ষতা'],['Clear communication, independent thinking, and teamwork.','স্পষ্ট যোগাযোগ, স্বাধীন চিন্তা ও দলগত দক্ষতা।']],
]
</script>
<template>
 <div class="learning-page">
  <section class="learning-hero" aria-labelledby="learning-title"><img :src="cover" :alt="text(['PIISC students working together','পিআইআইএসসির শিক্ষার্থীদের দলগত কাজ'])" fetchpriority="high"/><div class="learning-width hero-copy"><p class="learning-eyebrow">{{ text(['OUR LEARNING AREAS','আমাদের শিক্ষার ক্ষেত্র']) }}</p><h1 id="learning-title">{{ text(['Growing minds, strong character, purposeful futures.','বিকশিত মন, সুন্দর চরিত্র, অর্থবহ ভবিষ্যৎ।']) }}</h1><p>{{ text(['At Peace International Islamic School & College, learning connects knowledge with faith and everyday life, helping students grow from Grade 1 through Grade 12.','পিস ইন্টারন্যাশনাল ইসলামিক স্কুল অ্যান্ড কলেজে জ্ঞান, বিশ্বাস ও দৈনন্দিন জীবনের সংযোগ প্রথম থেকে দ্বাদশ শ্রেণি পর্যন্ত শিক্ষার্থীদের বিকাশে সাহায্য করে।']) }}</p></div></section>
  <section class="learning-width areas-section" :aria-label="text(['Learning areas at PIISC','পিআইআইএসসির শিক্ষার ক্ষেত্র'])"><div class="areas-grid"><article v-for="area in areas" :key="area.title[0]"><p class="learning-eyebrow">{{ text(area.tag) }}</p><h2>{{ text(area.title) }}</h2><p>{{ text(area.body) }}</p></article></div></section>
  <section class="learning-width features-section" aria-labelledby="features-title"><p class="learning-eyebrow">{{ text(['THE PIISC LEARNING EXPERIENCE','পিআইআইএসসির শিক্ষার অভিজ্ঞতা']) }}</p><h2 id="features-title">{{ text(['What shapes learning at PIISC','পিআইআইএসসির শিক্ষার ভিত্তি']) }}</h2><div class="features-grid"><article v-for="feature in features" :key="feature[0][0]"><h3>{{ text(feature[0]) }}</h3><p>{{ text(feature[1]) }}</p></article></div></section>
  <section class="learning-width learning-closing" aria-labelledby="closing-title"><p class="learning-eyebrow">{{ text(['KNOWLEDGE, FAITH & CHARACTER','জ্ঞান, বিশ্বাস ও চরিত্র']) }}</p><p>{{ text(['Our aim is to help young people approach learning with curiosity, treat others with compassion, and use their abilities responsibly. Together with families, PIISC supports a journey towards confidence, understanding, and a meaningful future.','আমাদের লক্ষ্য তরুণদের কৌতূহল নিয়ে শিখতে, সহমর্মিতার সঙ্গে আচরণ করতে এবং দায়িত্বশীলভাবে নিজের সামর্থ্য ব্যবহার করতে সাহায্য করা। পরিবারের সঙ্গে পিআইআইএসসি আত্মবিশ্বাস, বোঝাপড়া ও অর্থবহ ভবিষ্যতের পথে এগিয়ে যায়।']) }}</p><h2 id="closing-title">{{ text(['Modern Education With Islamic Values','ইসলামী মূল্যবোধের সঙ্গে আধুনিক শিক্ষা']) }}</h2></section>
 </div>
</template>
<style scoped>
.learning-page{background:#fff;color:#0a2948}.learning-width{width:calc(100% - clamp(32px,6.5vw,128px));max-width:1800px;margin-inline:auto}.learning-hero{position:relative;isolation:isolate;overflow:hidden;background:#0a2948}.learning-hero>img{position:absolute;inset:0;z-index:-2;width:100%;height:100%;object-fit:cover}.learning-hero::after{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(100deg,#294e9ef5,#294e9edb 65%,#0a2948bc)}.hero-copy{padding-block:clamp(64px,7vw,112px)}.learning-eyebrow{color:#b08a29;font-size:12px;font-weight:700;letter-spacing:.17em;line-height:1.6;margin-bottom:16px}.hero-copy .learning-eyebrow{color:#f3cc48;margin-bottom:24px}.hero-copy h1{font-size:clamp(36px,5vw,74px);line-height:1.12;color:white;max-width:1100px;margin-bottom:28px}.hero-copy>p:last-child{color:#edf2fa;max-width:980px;font-size:clamp(17px,1.4vw,22px);line-height:1.8}.areas-section{padding-block:64px 40px}.areas-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.areas-grid article{padding:clamp(24px,2.5vw,38px);border:1px solid #dde5f1;border-radius:6px;box-shadow:0 12px 36px #173a6a08;transition:transform .3s,border-color .3s,box-shadow .3s}.areas-grid article:hover{transform:translateY(-4px);border-color:#d9b33d;box-shadow:0 18px 40px #173a6a12}.areas-grid h2{font-size:clamp(23px,2vw,30px);line-height:1.3;color:#294e9e;margin-bottom:18px}.areas-grid article>p:last-child,.features-grid p{font-size:17px;color:#5d6e86;line-height:1.85}.features-section{padding-block:32px 48px}.features-section>h2{color:#294e9e;font-size:clamp(30px,3.5vw,50px);line-height:1.2;margin-bottom:32px}.features-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.features-grid article{padding:28px;border:1px solid #e4dfd3;border-radius:6px;background:#fcf5e6}.features-grid h3{color:#294e9e;font-size:22px;line-height:1.4;margin-bottom:14px}.learning-closing{text-align:center;padding-block:64px 80px}.learning-closing>p:not(.learning-eyebrow){max-width:980px;margin-inline:auto;font-size:20px;line-height:1.85;color:#5d6e86}.learning-closing h2{color:#294e9e;font-size:clamp(24px,2.3vw,34px);line-height:1.4;margin-top:26px}@media(max-width:900px){.features-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.areas-grid,.features-grid{grid-template-columns:1fr;gap:16px}.areas-section{padding-top:40px}.learning-closing{padding-block:36px 48px}.learning-closing>p:not(.learning-eyebrow){font-size:17px}}@media(prefers-reduced-motion:reduce){.areas-grid article{transition:none}.areas-grid article:hover{transform:none}}
</style>
