<script setup>
import { computed, ref } from 'vue'
import { newsEvents } from '../data/newsEvents.js'
import { useI18n } from '../composables/useI18n.js'
import NewsEventCard from '../components/NewsEventCard.vue'
import orientationPhoto from '../assets/images/orientation-program-chairman-speech.jpg'

const { language } = useI18n()
const tr = (en, bn) => language.value === 'bn' ? bn : en
const selected = ref('all')
const filters = [{ key: 'all', en: 'All stories', bn: 'সব খবর' }, { key: 'news', en: 'News', bn: 'সংবাদ' }, { key: 'event', en: 'Events', bn: 'অনুষ্ঠান' }]
const filtered = computed(() => selected.value === 'all' ? newsEvents : newsEvents.filter(item => item.category === selected.value))
</script>

<template>
  <main>
    <section class="news-hero [&&]:flex [@media(max-width:600px)]:[&&]:min-h-[320px] [@media(width>600px)]:[&&]:min-h-[380px] [&&]:items-center [&&]:[background-image:linear-gradient(90deg,#173f8eee,#244b9ecb),var(--hero-image)] [&&]:[background-size:cover] [&&]:[background-position:center_46%] [&&]:[color:white]" :style="{ '--hero-image': `url(${orientationPhoto})` }" aria-labelledby="news-page-title"><div class="news-container [&&&]:max-w-[1500px] [&&&]:[margin-inline-end:auto] [&&&]:[margin-inline-start:auto] [&&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:600px)]:[&&&]:[padding-block-end:52px] [@media(width>600px)]:[&&&]:[padding-block-end:75px] [@media(max-width:600px)]:[&&&]:[padding-block-start:52px] [@media(width>600px)]:[&&&]:[padding-block-start:75px]"><p class="[&&]:[font-size:12px] [&&]:mb-[15px] [&&]:font-[800] [&&]:tracking-[0.17em] [&&]:[color:rgb(244,_197,_55)]">{{ tr('PIISC NEWS & EVENTS', 'পিআইআইএসসির সংবাদ ও অনুষ্ঠান') }}</p><h1 class="[&&]:[font-size:clamp(40px,_5vw,_72px)] [&&]:max-w-[920px] [&&]:leading-[1.1] [&&]:m-[0px_0px_22px_0px]" id="news-page-title">{{ tr('Stories from our school community.', 'আমাদের বিদ্যালয় পরিবারের গল্প।') }}</h1><span class="[@media(max-width:600px)]:[&&]:[font-size:16px] [@media(width>600px)]:[&&]:[font-size:18px] [&&]:block [&&]:max-w-[680px] [&&]:leading-[1.65]">{{ tr('Explore moments from our 2026 orientation programme and life at PIISC.', '২০২৬ সালের ওরিয়েন্টেশন অনুষ্ঠান এবং পিআইআইএসসির নানা মুহূর্ত দেখুন।') }}</span></div></section>
    <section class="news-listing [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(244,_247,_252)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [@media(max-width:600px)]:[&&]:p-[52px_0px_65px_0px] [@media(width>600px)]:[&&]:p-[75px_0px_95px_0px]"><div class="news-container [&&]:max-w-[1500px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))]"><div class="listing-heading [&&]:mb-[30px] [&&]:flex [&&]:justify-between [&&]:gap-x-[25px] [&&]:gap-y-[25px] [@media(max-width:900px)]:[&&]:[align-items:start] [@media(width>900px)]:[&&]:[align-items:end] [@media(max-width:900px)]:[&&]:flex-col"><div><p class="listing-eyebrow [&&]:[font-size:12px] [&&]:mb-[15px] [&&]:font-[800] [&&]:tracking-[0.17em] [&&]:[color:rgb(244,_197,_55)]">{{ tr('LATEST STORIES', 'সাম্প্রতিক গল্প') }}</p><h2 class="[&&]:[color:rgb(36,_75,_158)] [&&]:[font-size:clamp(30px,_3.2vw,_48px)] [&&]:m-[0px]">{{ tr('News & Events', 'সংবাদ ও অনুষ্ঠান') }}</h2></div><div class="news-filters [&&]:flex [&&]:flex-wrap [&&]:gap-x-[8px] [&&]:gap-y-[8px]" role="group" :aria-label="tr('Filter stories', 'খবর বাছাই করুন')"><button class="[&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:white] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:[color:rgb(36,_75,_158)] [&&]:[font-size:14px] [&&]:font-[750] [&&]:p-[10px_17px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(203,_216,_239)] [.news-filters_button&.active]:[background-color:rgb(36,_75,_158)] [.news-filters_button&.active]:[color:white] [.news-filters_button&.active]:[border-color:rgb(36,_75,_158)] [.news-filters_button&:hover:not(.active)]:[background-color:rgb(234,_241,_254)]" v-for="filter in filters" :key="filter.key" type="button" :class="{ active: selected === filter.key }" :aria-pressed="selected === filter.key" @click="selected = filter.key">{{ tr(filter.en, filter.bn) }}</button></div></div><div class="listing-grid [&&]:grid [@media(max-width:600px)]:[&&]:grid-cols-[1fr] [@media(width>600px)_and_(max-width:900px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [@media(width>900px)]:[&&]:grid-cols-[repeat(3,_minmax(0px,_1fr))] [&&]:gap-x-[22px] [&&]:gap-y-[22px]"><NewsEventCard v-for="item in filtered" :key="item.slug" :item="item" /></div></div></section>
  </main>
</template>
