<script setup>
import community from '../assets/images/girls-group.jpg'
import { useI18n } from '../composables/useI18n.js'
const { language } = useI18n()
const copy = (en, bn) => language.value === 'bn' ? bn : en
</script>

<template>
  <div class="vision-page [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:initial] [&&]:[background-image:linear-gradient(rgb(255,_255,_255),_rgb(248,_249,_252))] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(10,_41,_72)]">
    <section class="vision-hero [&&]:relative [&&]:isolate [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(10,_41,_72)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&.vision-hero::after]:absolute [&.vision-hero::after]:bottom-[0px] [&.vision-hero::after]:left-[0px] [&.vision-hero::after]:right-[0px] [&.vision-hero::after]:top-[0px] [&.vision-hero::after]:z-[-1] [&.vision-hero::after]:[background-attachment:initial] [&.vision-hero::after]:[background-clip:initial] [&.vision-hero::after]:[background-color:initial] [&.vision-hero::after]:[background-image:linear-gradient(100deg,_rgba(41,_78,_158,_0.96)_5%,_rgba(41,_78,_158,_0.86)_60%,_rgba(10,_41,_72,_0.737))] [&.vision-hero::after]:[background-origin:initial] [&.vision-hero::after]:[background-position:initial] [&.vision-hero::after]:[background-repeat:initial] [&.vision-hero::after]:[background-size:initial] [&.vision-hero::after]:[content:'']" aria-labelledby="vision-page-title">
      <img class="[&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:z-[-2] [&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [@media(max-width:760px)]:[&&]:[object-position:65%_center] [@media(width>760px)]:[&&]:[object-position:center_38%]" :src="community" :alt="copy('Students in the PIISC school community', 'পিআইআইএসসির শিক্ষার্থীরা')" fetchpriority="high" />
      <div class="vision-width vision-hero-content [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [@media(max-width:760px)]:[&&]:[padding-block-end:64px] [@media(width>760px)]:[&&]:[padding-block-end:clamp(64px,_7.5vw,_132px)] [@media(max-width:760px)]:[&&]:[padding-block-start:56px] [@media(width>760px)]:[&&]:[padding-block-start:clamp(64px,_7.5vw,_132px)]">
        <p class="vision-eyebrow [&&&]:[color:rgb(243,_204,_72)] [&&&]:[font-size:clamp(12px,_1vw,_17px)] [&&&]:font-[700] [&&&]:uppercase [&&&]:tracking-[0.18em] [&&&]:m-[0px_0px_24px_0px]">{{ copy('VISION & MISSION', 'ভিশন ও মিশন') }}</p>
        <h1 class="[&&]:max-w-[1230px] [&&]:[color:white] [@media(max-width:760px)]:[&&]:[font-size:clamp(34px,_6vw,_46px)] [@media(width>760px)]:[&&]:[font-size:clamp(36px,_5.2vw,_88px)] [&&]:leading-[1.1] [&&]:[text-wrap-mode:initial] [&&]:[text-wrap-style:balance] [&&]:m-[0px_0px_28px_0px]" id="vision-page-title">{{ copy('Knowledge with purpose. Faith in action. Leadership with compassion.', 'উদ্দেশ্যপূর্ণ জ্ঞান। কর্মে বিশ্বাস। সহমর্মিতায় নেতৃত্ব।') }}</h1>
        <p class="vision-lead [&&]:max-w-[1020px] [&&]:[color:rgb(237,_241,_248)] [&&]:[font-size:clamp(17px,_1.55vw,_26px)] [&&]:leading-[1.75]">{{ copy('Our aspirations for learning, character, and the partnership between school and family at Peace International Islamic School & College.', 'পিস ইন্টারন্যাশনাল ইসলামিক স্কুল অ্যান্ড কলেজে শিক্ষা, চরিত্র গঠন এবং স্কুল ও পরিবারের অংশীদারিত্ব নিয়ে আমাদের প্রত্যাশা।') }}</p>
      </div>
    </section>
    <section class="vision-width vision-statements [&&]:max-w-[1800px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))] [&&]:grid [@media(max-width:760px)]:[&&]:grid-cols-[1fr] [@media(width>760px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [&&]:gap-x-[clamp(20px,_2vw,_32px)] [&&]:gap-y-[clamp(20px,_2vw,_32px)] [&&]:[padding-block-end:48px] [&&]:[padding-block-start:clamp(40px,_4.5vw,_80px)] [@media(max-width:760px)]:[&&]:pb-[30px]" :aria-label="copy('Our vision and mission', 'আমাদের ভিশন ও মিশন')">
      <article class="statement-card [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[box-shadow:rgba(23,_58,_106,_0.024)_0px_14px_40px] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.3s,_0.3s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:box-shadow,_border-color] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [&&]:p-[clamp(26px,_2.5vw,_44px)] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_227,_238)] [&.statement-card:hover]:[box-shadow:rgba(23,_58,_106,_0.063)_0px_18px_44px] [&.statement-card:hover]:[border-color:rgb(207,_180,_102)]" aria-labelledby="vision-heading">
        <h2 id="vision-heading" class="vision-eyebrow [&&]:[color:rgb(179,_139,_44)] [&&]:[font-size:clamp(13px,_1vw,_17px)] [&&]:font-[700] [&&]:uppercase [&&]:!tracking-[0.18em] [&&]:leading-[1.5] [&&]:m-[0px_0px_20px_0px]">{{ copy('VISION', 'আমাদের ভিশন') }}</h2>
        <p class="[&&]:[font-size:clamp(17px,_1.5vw,_25px)] [&&]:leading-[1.85] [&&]:[color:rgb(93,_110,_134)]">{{ copy('We envision a generation of confident learners whose knowledge is guided by faith, good character, and care for others. PIISC aspires to help young people grow into thoughtful, capable individuals who continue learning throughout life and make a positive contribution to their families, communities, and the wider world.', 'আমরা এমন এক আত্মবিশ্বাসী প্রজন্মের স্বপ্ন দেখি, যাদের জ্ঞান পরিচালিত হবে বিশ্বাস, সুন্দর চরিত্র ও মানুষের প্রতি যত্নের মাধ্যমে। পিআইআইএসসি তরুণদের চিন্তাশীল ও দক্ষ মানুষ হিসেবে গড়ে তুলতে চায়, যারা সারা জীবন শিখবে এবং পরিবার, সমাজ ও বৃহত্তর বিশ্বে ইতিবাচক অবদান রাখবে।') }}</p>
      </article>
      <article class="statement-card mission-card [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(252,_245,_230)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[box-shadow:rgba(23,_58,_106,_0.024)_0px_14px_40px] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.3s,_0.3s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:box-shadow,_border-color] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [&&]:p-[clamp(26px,_2.5vw,_44px)] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(229,_223,_211)] [&.statement-card:hover]:[box-shadow:rgba(23,_58,_106,_0.063)_0px_18px_44px] [&.statement-card:hover]:[border-color:rgb(207,_180,_102)]" aria-labelledby="mission-heading">
        <h2 id="mission-heading" class="vision-eyebrow [&&]:[color:rgb(179,_139,_44)] [&&]:[font-size:clamp(13px,_1vw,_17px)] [&&]:font-[700] [&&]:uppercase [&&]:!tracking-[0.18em] [&&]:leading-[1.5] [&&]:m-[0px_0px_20px_0px]">{{ copy('MISSION', 'আমাদের মিশন') }}</h2>
        <p class="[&&]:[font-size:clamp(17px,_1.5vw,_25px)] [&&]:leading-[1.85] [&&]:[color:rgb(93,_110,_134)]">{{ copy('Our mission is to bring modern education and Islamic values together in a supportive learning community. We aim to encourage curiosity, clear communication, creativity, and independent thinking while building habits of honesty, respect, and responsibility. Through meaningful learning experiences and collaboration with families, we seek to prepare students for both academic progress and a purposeful life.', 'আমাদের মিশন হলো একটি সহায়ক শিক্ষাঙ্গনে আধুনিক শিক্ষা ও ইসলামী মূল্যবোধকে একত্র করা। সততা, শ্রদ্ধা ও দায়িত্ববোধ গড়ে তোলার পাশাপাশি আমরা কৌতূহল, স্পষ্ট যোগাযোগ, সৃজনশীলতা ও স্বাধীন চিন্তাকে উৎসাহিত করতে চাই। অর্থবহ শিক্ষার অভিজ্ঞতা এবং পরিবারের সহযোগিতার মাধ্যমে আমরা শিক্ষার্থীদের প্রাতিষ্ঠানিক অগ্রগতি ও উদ্দেশ্যপূর্ণ জীবনের জন্য প্রস্তুত করতে চাই।') }}</p>
      </article>
    </section>
  </div>
</template>
