<script setup>
import { ArrowRight } from 'lucide-vue-next'
import { newsEvents } from '../data/newsEvents.js'
import { useI18n } from '../composables/useI18n.js'
import NewsEventCard from './NewsEventCard.vue'
const { language } = useI18n()
const tr = (en, bn) => language.value === 'bn' ? bn : en
</script>
<template>
  <section class="home-news [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(244,_247,_252)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [@media(max-width:620px)]:[&&]:p-[52px_0px_64px_0px] [@media(width>620px)]:[&&]:p-[76px_0px_88px_0px]" aria-labelledby="home-news-title"><div class="news-width [&&]:max-w-[1500px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))]">
    <div class="news-heading [&&]:relative [@media(max-width:620px)]:[&&]:mb-[27px] [@media(width>620px)]:[&&]:mb-[44px] [@media(max-width:620px)]:[&&]:block [@media(width>620px)]:[&&]:flex [&&]:items-center [&&]:justify-center [@media(max-width:620px)]:[&&]:text-center"><div class="heading-center [&&]:text-center"><span class="news-label [&&]:inline-block [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(233,_241,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(36,_75,_158)] [&&]:[font-size:12px] [&&]:font-[800] [&&]:tracking-[0.18em] [&&]:p-[8px_19px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(197,_216,_251)]">{{ tr('LATEST', 'সর্বশেষ') }}</span><h2 class="[&&]:[color:rgb(23,_63,_142)] [&&]:[font-size:clamp(32px,_3.3vw,_48px)] [&&]:m-[12px_0px_11px_0px]" id="home-news-title">{{ tr('News & Events', 'সংবাদ ও অনুষ্ঠান') }}</h2><span class="heading-rule [&&]:block [&&]:h-[4px] [&&]:w-[68px] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(213,_167,_42)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:m-[auto]" aria-hidden="true"></span></div><RouterLink to="/news" class="view-all [@media(max-width:620px)]:[&&]:static [@media(width>620px)]:[&&]:absolute [&&]:right-[0px] [&&]:top-[50%] [&&]:inline-flex [&&]:items-center [&&]:justify-center [&&]:gap-x-[7px] [&&]:gap-y-[7px] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(36,_75,_158)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:white] [&&]:[font-size:14px] [@media(max-width:620px)]:[&&]:[transform:none] [@media(width>620px)]:[&&]:[transform:translateY(-50%)] [&&]:font-[800] [@media(max-width:620px)]:[&&]:mt-[22px] [&&]:p-[12px_24px] [&.view-all:hover]:[background-color:rgb(23,_58,_128)]">{{ tr('View all', 'সব দেখুন') }} <ArrowRight :size="18" aria-hidden="true" /></RouterLink></div>
    <div class="home-news-grid [&&]:grid [@media(max-width:620px)]:[&&]:grid-cols-[1fr] [@media(width>620px)_and_(max-width:850px)]:[&&]:grid-cols-[repeat(2,_minmax(0px,_1fr))] [@media(width>850px)]:[&&]:grid-cols-[repeat(3,_minmax(0px,_1fr))] [&&]:gap-x-[22px] [&&]:gap-y-[22px]"><NewsEventCard class="[@media(max-width:620px)]:[.home-news-grid>&:last-child]:flex [@media(width>620px)_and_(max-width:850px)]:[.home-news-grid>&:last-child]:hidden" v-for="item in newsEvents.slice(0, 3)" :key="item.slug" :item="item" /></div>
  </div></section>
</template>
