<script setup>
import { ArrowUpRight, Mail, MapPin, Phone } from 'lucide-vue-next'
import { address, schoolDirectionsUrl, schoolMapEmbedUrl, schoolMapUrl } from '../data/content.js'
import { headerContacts } from '../data/navigation.js'
import { useI18n } from '../composables/useI18n.js'

const { language } = useI18n()
const tr = (en, bn) => language.value === 'bn' ? bn : en
const phoneUrl = `tel:${headerContacts.phone.replace(/\s/g, '')}`
</script>

<template>
  <section class="home-location [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_249,_236)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [@media(max-width:600px)]:[&&]:p-[48px_0px_60px_0px] [@media(width>600px)]:[&&]:p-[72px_0px_84px_0px]" aria-labelledby="home-location-title">
    <div class="location-width [&&]:max-w-[1500px] [&&]:[margin-inline-end:auto] [&&]:[margin-inline-start:auto] [&&]:w-[calc(100%_-_clamp(32px,_6.5vw,_128px))]">
      <header class="location-heading [@media(max-width:600px)]:[&&]:mb-[26px] [@media(width>600px)]:[&&]:mb-[36px] [&&]:text-center">
        <span class="location-label [&&]:inline-block [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(237,_243,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:[color:rgb(41,_78,_158)] [&&]:[font-size:12px] [&&]:font-[800] [&&]:tracking-[0.17em] [&&]:p-[8px_18px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(199,_217,_250)]">{{ tr('LOCATION', 'অবস্থান') }}</span>
        <h2 class="[&&]:[color:rgb(41,_78,_158)] [&&]:[font-size:clamp(34px,_3.5vw,_52px)] [&&]:m-[13px_0px_8px_0px]" id="home-location-title">{{ tr('Find PIISC', 'পিআইআইএসসি খুঁজে নিন') }}</h2>
        <p class="[&&]:[color:rgb(83,_105,_137)] [&&]:[font-size:16px]">{{ tr('Visit us in Ashulia, Savar, Dhaka.', 'ঢাকার সাভারের আশুলিয়ায় আমাদের ক্যাম্পাসে আসুন।') }}</p>
      </header>
      <div class="location-card [&&]:grid [@media(max-width:850px)]:[&&]:grid-cols-[1fr] [@media(width>850px)]:[&&]:grid-cols-[minmax(0px,_1.9fr)_minmax(300px,_0.9fr)] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[border-bottom-left-radius:12px] [&&]:[border-bottom-right-radius:12px] [&&]:[border-top-left-radius:12px] [&&]:[border-top-right-radius:12px] [&&]:[box-shadow:rgba(41,_78,_158,_0.08)_0px_20px_48px] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(220,_227,_240)]">
        <div class="map-wrap [@media(max-width:600px)]:[&&]:min-h-[300px] [@media(width>600px)_and_(max-width:850px)]:[&&]:min-h-[350px] [@media(width>850px)]:[&&]:min-h-[440px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(233,_239,_250)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:relative">
          <iframe class="[&&]:block [&&]:h-[100%] [@media(max-width:600px)]:[&&]:min-h-[300px] [@media(width>600px)_and_(max-width:850px)]:[&&]:min-h-[350px] [@media(width>850px)]:[&&]:min-h-[440px] [&&]:w-[100%] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:[border-width:0px] [&&]:[border-style:none] [&&]:[border-color:currentcolor]"
            :src="schoolMapEmbedUrl"
            :title="tr('Google Map showing the PIISC address in Ashulia', 'আশুলিয়ায় পিআইআইএসসির ঠিকানার গুগল ম্যাপ')"
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
            allowfullscreen
          ></iframe>
          <a class="map-open [&&]:absolute [&&]:bottom-[0px] [&&]:left-[0px] [&&]:right-[0px] [&&]:top-[0px] [&&]:flex [&&]:items-end [&&]:justify-end [&&]:[color:rgb(255,_255,_255)] [&&]:p-[16px]" :href="schoolMapUrl" target="_blank" rel="noopener noreferrer" :aria-label="tr('Open the exact school location in Google Maps', 'গুগল ম্যাপে স্কুলের সঠিক অবস্থান খুলুন')">
            <span class="[&&]:inline-flex [&&]:items-center [&&]:gap-x-[7px] [&&]:gap-y-[7px] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(35,_75,_145)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[font-size:14px] [&&]:font-[800] [&&]:[box-shadow:rgba(0,_0,_0,_0.2)_0px_4px_16px] [&&]:p-[10px_14px] [.map-open:hover_span&]:[background-color:rgb(23,_57,_105)] [.map-open:focus-visible_span&]:[background-color:rgb(23,_57,_105)]">{{ tr('Open in Google Maps', 'গুগল ম্যাপে খুলুন') }} <ArrowUpRight :size="18" aria-hidden="true" /></span>
          </a>
        </div>
        <aside class="location-details [&&]:flex [&&]:flex-col [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(35,_75,_145)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(255,_255,_255)] [@media(max-width:850px)]:[&&]:gap-x-[0px] [@media(max-width:850px)]:[&&]:gap-y-[0px] [@media(max-width:600px)]:[&&]:p-[27px_23px] [@media(width>600px)]:[&&]:p-[34px_30px]">
          <div class="location-details-heading [&&]:flex [&&]:items-center [&&]:gap-x-[11px] [&&]:gap-y-[11px] [&&]:pb-[16px] [&&]:[border-bottom-color:rgba(255,_255,_255,_0.314)] [&&]:[border-bottom-style:solid] [&&]:[border-bottom-width:1px]"><MapPin class="[&&]:[color:rgb(229,_181,_50)] [&&]:[flex-basis:auto] [&&]:[flex-grow:0] [&&]:[flex-shrink:0]" :size="24" aria-hidden="true" /><h3 class="[&&]:[font-size:24px] [&&]:m-[0px]">{{ tr('Our location', 'আমাদের অবস্থান') }}</h3></div>
          <div class="location-detail [&&]:mt-[24px] [&&]:flex [&&]:items-start [&&]:gap-x-[16px] [&&]:gap-y-[16px] [&&]:[font-size:15px] [&&]:leading-[1.6]"><MapPin class="[&&]:[color:rgb(229,_181,_50)] [&&]:[flex-basis:auto] [&&]:[flex-grow:0] [&&]:[flex-shrink:0]" :size="20" aria-hidden="true" /><div><strong class="[&&]:[font-size:15px]">{{ tr('Peace International Islamic School & College', 'পিস ইন্টারন্যাশনাল ইসলামিক স্কুল অ্যান্ড কলেজ') }}</strong><p class="[&&]:mt-[5px] [&&]:[color:rgb(227,_236,_252)]">{{ tr(address, 'দ্য হোয়াইট প্যালেস ইউনিক, ১৩৪৯ ঢাকা–আশুলিয়া মহাসড়ক, বাইপাইল') }}</p></div></div>
          <div class="location-detail [&&]:mt-[24px] [&&]:flex [&&]:items-start [&&]:gap-x-[16px] [&&]:gap-y-[16px] [&&]:[font-size:15px] [&&]:leading-[1.6]"><Phone class="[&&]:[color:rgb(229,_181,_50)] [&&]:[flex-basis:auto] [&&]:[flex-grow:0] [&&]:[flex-shrink:0]" :size="20" aria-hidden="true" /><a class="[&&]:[overflow-wrap:anywhere] [.location-detail_a&:hover]:[text-decoration:underline] [.location-detail_a&:hover]:[text-decoration-color:initial] [.location-detail_a&:hover]:[text-decoration-line:underline] [.location-detail_a&:hover]:[text-decoration-style:initial] [.location-detail_a&:hover]:[text-decoration-thickness:initial]" :href="phoneUrl">{{ headerContacts.phone.trim() }}</a></div>
          <div class="location-detail [&&]:mt-[24px] [&&]:flex [&&]:items-start [&&]:gap-x-[16px] [&&]:gap-y-[16px] [&&]:[font-size:15px] [&&]:leading-[1.6]"><Mail class="[&&]:[color:rgb(229,_181,_50)] [&&]:[flex-basis:auto] [&&]:[flex-grow:0] [&&]:[flex-shrink:0]" :size="20" aria-hidden="true" /><a class="[&&]:[overflow-wrap:anywhere] [.location-detail_a&:hover]:[text-decoration:underline] [.location-detail_a&:hover]:[text-decoration-color:initial] [.location-detail_a&:hover]:[text-decoration-line:underline] [.location-detail_a&:hover]:[text-decoration-style:initial] [.location-detail_a&:hover]:[text-decoration-thickness:initial]" :href="`mailto:${headerContacts.email}`">{{ headerContacts.email }}</a></div>
          <a class="map-directions [@media(max-width:850px)]:[&&]:mt-[28px] [@media(width>850px)]:[&&]:mt-[auto] [&&]:flex [&&]:min-h-[48px] [&&]:items-center [&&]:justify-center [&&]:gap-x-[8px] [&&]:gap-y-[8px] [&&]:[border-bottom-left-radius:6px] [&&]:[border-bottom-right-radius:6px] [&&]:[border-top-left-radius:6px] [&&]:[border-top-right-radius:6px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(228,_177,_46)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(20,_45,_86)] [&&]:[font-size:14px] [&&]:text-center [&&]:font-[800] [&&]:[transition-behavior:normal] [&&]:[transition-delay:0s] [&&]:[transition-duration:0.2s] [&&]:[transition-property:background] [&&]:[transition-timing-function:ease] [&&]:p-[10px_16px] [&.map-directions:hover]:[background-color:rgb(240,_197,_78)] [&.map-directions:focus-visible]:[outline-color:white] [&.map-directions:focus-visible]:[outline-style:solid] [&.map-directions:focus-visible]:[outline-width:3px] [&.map-directions:focus-visible]:[outline-offset:3px]" :href="schoolDirectionsUrl" target="_blank" rel="noopener noreferrer">{{ tr('Get directions on Google Maps', 'গুগল ম্যাপে পথ দেখুন') }} <ArrowUpRight :size="19" aria-hidden="true" /></a>
        </aside>
      </div>
    </div>
  </section>
</template>
