<script setup>
import { ArrowRight } from 'lucide-vue-next'
import { useI18n } from '../composables/useI18n.js'
defineProps({ item: { type: Object, required: true } })
const { language } = useI18n()
const tr = (en, bn) => language.value === 'bn' ? bn : en
</script>
<template>
  <article class="event-card [&&]:min-w-[0px] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(255,_255,_255)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[border-image-outset:0] [&&]:[border-image-repeat:stretch] [&&]:[border-image-slice:100%] [&&]:[border-image-source:none] [&&]:[border-image-width:1] [&&]:flex [&&]:flex-col [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[border-bottom-left-radius:12px] [&&]:[border-bottom-right-radius:12px] [&&]:[border-top-left-radius:12px] [&&]:[border-top-right-radius:12px] [&&]:[box-shadow:rgba(23,_58,_106,_0.047)_0px_12px_32px] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-behavior:normal,_normal] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-behavior:normal] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-delay:0s,_0s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.25s,_0.25s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:transform,_box-shadow] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-timing-function:ease,_ease] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-timing-function:ease] [&&]:[border-width:1px] [&&]:[border-style:solid] [&&]:[border-color:rgb(224,_231,_243)] [&.event-card:hover]:[box-shadow:rgba(23,_58,_106,_0.11)_0px_18px_36px] [@media(prefers-reduced-motion:no-preference)]:[&.event-card:hover]:[transform:translateY(-4px)] [@media(prefers-reduced-motion:reduce)]:[&.event-card:hover]:[transform:none]">
    <RouterLink :to="`/news/${item.slug}`" class="event-image [&&]:relative [&&]:block [&&]:overflow-x-hidden [&&]:overflow-y-hidden [&&]:[aspect-ratio:1.72_/_1] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(232,_238,_248)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial]" :aria-label="item.title[language]"><img class="[&&]:h-[100%] [&&]:w-[100%] [&&]:object-cover [&&]:[transition-behavior:normal] [&&]:[transition-delay:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-duration:0.4s] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-duration:0s] [@media(prefers-reduced-motion:no-preference)]:[&&]:[transition-property:transform] [@media(prefers-reduced-motion:reduce)]:[&&]:[transition-property:none] [&&]:[transition-timing-function:ease] [@media(prefers-reduced-motion:no-preference)]:[.event-card:hover_.event-image_img&]:[transform:scale(1.04)] [@media(prefers-reduced-motion:reduce)]:[.event-card:hover_.event-image_img&]:[transform:none]" :src="item.image" :alt="item.title[language]" loading="lazy" width="600" height="360" /><span class="[&&]:absolute [&&]:top-[14px] [&&]:left-[14px] [&&]:[border-bottom-left-radius:100px] [&&]:[border-bottom-right-radius:100px] [&&]:[border-top-left-radius:100px] [&&]:[border-top-right-radius:100px] [&&]:tracking-[0.08em] [&&]:[background-attachment:initial] [&&]:[background-clip:initial] [&&]:[background-color:rgb(223,_172,_40)] [&&]:[background-image:initial] [&&]:[background-origin:initial] [&&]:[background-position:initial] [&&]:[background-repeat:initial] [&&]:[background-size:initial] [&&]:[color:rgb(20,_54,_110)] [&&]:[font-size:11px] [&&]:font-[800] [&&]:p-[7px_13px]">{{ item.category === 'news' ? tr('NEWS', 'সংবাদ') : tr('EVENT', 'অনুষ্ঠান') }}</span></RouterLink>
    <div class="event-content [&&]:flex [&&]:flex-col [&&]:items-start [&&]:[flex-basis:0%] [&&]:[flex-grow:1] [&&]:[flex-shrink:1] [&&]:p-[22px]"><p class="event-meta [&&]:mb-[10px] [&&]:[color:rgb(96,_113,_142)] [&&]:[font-size:12px]">{{ tr('PIISC · Orientation', 'পিআইআইএসসি · ওরিয়েন্টেশন') }} {{ item.year }}</p><h3 class="[&&]:[font-size:21px] [&&]:leading-[1.35] [&&]:[color:rgb(23,_63,_142)] [&&]:m-[0px_0px_10px_0px]"><RouterLink class="[.event-content_h3_a&:hover]:[color:rgb(12,_45,_109)]" :to="`/news/${item.slug}`">{{ item.title[language] }}</RouterLink></h3><p class="event-excerpt [&&]:[font-size:15px] [&&]:mb-[19px] [&&]:leading-[1.65] [&&]:[color:rgb(83,_105,_137)]">{{ item.excerpt[language] }}</p><RouterLink :to="`/news/${item.slug}`" class="event-read [&&]:mt-[auto] [&&]:inline-flex [&&]:items-center [&&]:gap-x-[6px] [&&]:gap-y-[6px] [&&]:[color:rgb(36,_75,_158)] [&&]:[font-size:14px] [&&]:font-[800] [&.event-read:hover]:[text-decoration:underline] [&.event-read:hover]:[text-decoration-color:initial] [&.event-read:hover]:[text-decoration-line:underline] [&.event-read:hover]:[text-decoration-style:initial] [&.event-read:hover]:[text-decoration-thickness:initial]">{{ tr('Read story', 'বিস্তারিত পড়ুন') }} <ArrowRight :size="17" aria-hidden="true" /></RouterLink></div>
  </article>
</template>
